### ISSUE TITLE
Execute Anonymous sometimes gives non-related error

### ISSUE THREAD

**Issue by hpreets** [xjsender/haoide#100]
Sometimes when I run a code using execute anonymous, it give me this error

`expecting a left angle bracket, found '&' at line 1 column 40`

Then without any change, when I run again, it runs successfully. Do you think it is Sublime error related to some encoding?

**Comment by xjsender** [comment]
@hpreets , can you paste your code here.

**Comment by hpreets** [comment]
`Set<Id> shipToContactIds = new Set<Id>();
`

With this one too, it gave error the first time and successfully ran the next time. The error was

`expecting a left angle bracket, found '&' at line 1 column 40`

**Comment by xjsender** [comment]
@hpreets ， I can't replicate this issue, can you set ``debug_mode`` to ``true`` before you replicate this issue in your computer, I need the log message in your console, however, remember remove the session info in the log.

**Comment by hpreets** [comment]
Yeah I was expecting this might not be reproducible. I set the `debug_mode` to `true` but it does not even open the log messages in console when this error comes. So perhaps, it does not even reach Salesforce. May be some local issue but I have started seeing it in the last 1 month only.

**Comment by xjsender** [comment]
@hpreets , If you pen the debug mode, extra message will be output in the console but not open a new  view.

**Comment by hpreets** [comment]
Unfortunately, I do not get any additional message in the console either. :-(

**Comment by xjsender** [comment]
@hpreets , did this issue always happen in your side these days?

**Comment by lushang** [comment]
Closed for no response for years.
