### ISSUE TITLE
Invalid formatting for Apex class

### ISSUE THREAD

**Issue by eugene-vabishchevich** [xjsender/haoide#102]
Hey!

Just updated to new version. And when I open any apex class I see the following formatting http://take.ms/J2Inq

**Comment by xjsender** [comment]
@eugene-vabishchevich , you should restart sublime after new version is updated, and then reopen the class, it will be ok.

**Comment by eugene-vabishchevich** [comment]
@xjsender just tried, it didn't help

**Comment by xjsender** [comment]
@eugene-vabishchevich , I can't replicate your issue.

**Comment by xjsender** [comment]
Can you paste the console message after you restart the sublime?

**Comment by xjsender** [comment]
@eugene-vabishchevich , how is going with issue?

**Comment by eugenevabishchevich** [comment]
@xjsender it's sometime happens when OS crushed. So, I have to reinstall sublime and ide plugin. I don't know the reason of that actually...
