### ISSUE TITLE
Can't deploy code to the server 

### ISSUE THREAD

**Issue by 361love** [xjsender/haoide#104]
I have writen a test  class , I cant deploy it to the server  
![1](https://cloud.githubusercontent.com/assets/3375867/14272361/f8082950-fb34-11e5-86f5-bdf60033100d.png)

**Comment by xjsender** [comment]
@361love ， there is any console message?

**Comment by xjsender** [comment]
@361love , can you check you have seen the same issue with #101 ?

**Comment by xjsender** [comment]
@361love , how is going on with this issue?
