### ISSUE TITLE
Context menu becomes slow on all Salesforce component

### ISSUE THREAD

**Issue by Shababsoft** [xjsender/haoide#108]
Hello @xjsender ,

Since last update, context menu (right click window) is taking few seconds to popup. If I disable the haoide package, context menu popups without any delay. 

I am wandering if this is happening with me only or some else also has the same issue. It was working fine before last update.

**Comment by xjsender** [comment]
@Shababsoft , how many seconds to open the context menu for your side?

**Comment by Shababsoft** [comment]
4-7 seconds

**Comment by xjsender** [comment]
@Shababsoft , it seems too slow, 1.5 to 2 seconds for my side.

**Comment by xjsender** [comment]
@Shababsoft , there is a ``component_metadata.sublime-settings`` file in your sublime ``User`` path, how much is the size of this file? 

Some similar performance issue can be fixed by reinstall the sublime, I think you can try that.

**Comment by Shababsoft** [comment]
4.44 MB

**Comment by Shababsoft** [comment]
@xjsender can you add a functionality that creates a separate metadata file in project **.config** folder rather than maintaining the single file `component_metadata.sublime-settings`. I believe this will increase the performance of context menu and autocomplete on components.

**Comment by xjsender** [comment]
@Shababsoft , yes, I will try to do that as you wish, I will post a test version for your test to here once it's done.

**Comment by hpreets** [comment]
Thanks @xjsender I too am waiting for this change. It takes around 2 seconds to show the context menu which is a little more than what I would expect, having worked with HaoIDE for last 9 months :-) You see, we are now used to getting work done faster as opposed to the eclipse slow experience. :+1:

**Comment by xjsender** [comment]
@hpreets , Sorry for the problem, Actually, I wonder this change can't solve your problem, so I didn't make this change these days, whatever, I will try to start up this change this weekend.

Thanks for your support.

**Comment by xjsender** [comment]
@hpreets , I suggest you can use commands in ``command palette`` which has all the same commands with context menu.

**Comment by hpreets** [comment]
@xjsender That's good to know. Let me check that.

**Comment by hpreets** [comment]
For most of the time, I use Refresh From Server and Execute Anonymous commands from the HaoIDE Context Menu. These two do not show up in `command palette`. However I realized that we do have short-cut for these two commands. Hence for now, I think I am OK.

**Comment by xjsender** [comment]
@hpreets , I will add the missed commands in the command palette.

**Comment by xjsender** [comment]
@Shababsoft , @hpreets , I just checked the code and I try to cache the ``component metadata`` to memory, however, there is no effect to improve the performance.

I will try to investigate on it.

**Comment by xjsender** [comment]
@Shababsoft , @hpreets , just tried to cache the metadata to memory, it seems this solution is working.

**Comment by Shababsoft** [comment]
@xjsender please can you provide an option in the setting to enable to disable this feature? Do you know how much memory it will take?

**Comment by xjsender** [comment]
You can try it by yourself. New release is available.

**Comment by Shababsoft** [comment]
@xjsender  looks like performance has been improved. But I am getting the Conflict popup every-time I save a classes or page. I have restarted the sublime few time but still same issue.

**Comment by xjsender** [comment]
@Shababsoft , every time when you succeed to save the class to server, there will have a async thread to fetch the ``LastModifledDate`` of the class from server, and then keep it to local.

So if you start to save the class immediately after last save operation, the fetching thread is still in running, at the moment, the timestamp will not match, plugin will alert you.

As my thought, generally, it should have 30 seconds interval between two save operation, at least, it is ok for me.

If it is not ok for you, I think, we can consider to change the ``fetching thread`` to sync operation, however, it will spend more time to finish save operation.

So what do you think?

Thanks.

**Comment by xjsender** [comment]
@Shababsoft, @hpreets , I will close this issue, if you are still experiencing heavy performance problem, please reopen it.

@Shababsoft , if you still have ``conflict message`` problem, please reply in issue #95 .

Thanks.
