### ISSUE TITLE
taking too much time to save file on server

### ISSUE THREAD

**Issue by naveenila1221** [xjsender/haoide#110]
Hi,

IDE is taking too much time to save any file like (controller or vf page). Today(i.e., on 09/05/2016) we are facing this issue but earlier it is very fast. 

Is there any specific cause that is creating the issue.

**Comment by xjsender** [comment]
@naveenila1221 , your earlier plugin version and  current plugin version? any log information?

**Comment by naveenila1221** [comment]
@xjsender 
currently I am using v.3.3.9 of haoide. 
I created project in feb/2016 and working on till now. Haven't any issue while saving the file earlier.
Today it has been consumed all most 10 mins to save file.

**Comment by xjsender** [comment]
@naveenila1221 , I think it may be the issue of salesforce server, because it is ok from my side.

**Comment by xjsender** [comment]
@naveenila1221 , how is going on this problem? is it ok now?

**Comment by naveenila1221** [comment]
@xjsender  It is fine now. It was the problem with salesfroce server at that time.
