### ISSUE TITLE
Please do keep an confirmation check for save file to server 

### ISSUE THREAD

**Issue by naveenila1221** [xjsender/haoide#111]
@xjsender 

I am talking about:
Right click--> Hao IDE -->'Save To Server'

There is no dual time check for 'save to server' option similar to 'Refresh From Server'.

When I am in hurry to take the refresh copy but mistakenly clicked on 'save to server'

**Comment by xjsender** [comment]
@naveenila1221 , though this is a strange requirement, however, I can add  a setting to control whether need confirmation for save operation, default value of the setting will be set as ``false``, you can override the default setting by yourself.

**Comment by naveenila1221** [comment]
@xjsender 

Thank you. I will try to make this setting.

**Comment by naveenila1221** [comment]
Thanks

**Comment by xjsender** [comment]
@naveenila1221 , please don't close this issue, I will close it after new release is delivered.

**Comment by xjsender** [comment]
@naveenila1221 , I have added a new setting named ``confirm_on_save`` in the new release, its default value is ``false``, you can open it by yourself.

Thanks.
