### ISSUE TITLE
Feature Request: Migrate File(s)

### ISSUE THREAD

**Issue by Xtremefaith** [xjsender/haoide#113]
My current workflow revolves around working in a sandbox org BUT keeping my codebase in my production workspace where my GIT repo resides. This requires me to constantly need to migrate files from one project to the next

_For example if I need to create a new Class/Trigger, since I cannot do this on a production org I first have to **"switch project** to a sandbox, and then **HaoIDE**>**New**>**ApexClass**. Once that is created I take the file and its meta companion and copy them to my production org workspace so that GIT will recognize it and I work from there while deploying to which ever environment I want._

So I propose to add a **context menu** (both on the sidebar and within the open file) that allows us to migrate the file _(and its meta file if necessary)_ to another project space (even overwriting the current file if it exist).

**Here is a screenshot to help explain**

![image](https://cloud.githubusercontent.com/assets/1228550/15406819/db8d68f8-1dbc-11e6-962c-16b9f2e97f6b.png)

**This would do the following:**

![image](https://cloud.githubusercontent.com/assets/1228550/15408390/d84ce2ec-1dc4-11e6-8b80-b0cc6cf7fab3.png)

**Comment by xjsender** [comment]
@Xtremefaith ， why don't you use ``deploy to server `` command? You just want to keep the file into production workspace but not save it to server?

**Comment by Xtremefaith** [comment]
This is correct I want to save in workspace so that I can make commits to repository but in develop branch since its still not ready for release/deploy to production server

**Comment by xjsender** [comment]
@Xtremefaith , Ok, this feature will be delivered in next release, which is scheduled at this week.

You can see the information of this release in the branch ``r3.4.0``

**Comment by xjsender** [comment]
@Xtremefaith , your request feature is delivered in the new release, please tell your feedback to it.

**Comment by Xtremefaith** [comment]
Your response & implementation time is nothing short of amazing! Couple feedback notes:

- The report is backwards and slightly off, in the screenshot below I was in "Production" _(HaoIDE->switch project)_ but within the sidebar I was in "Beta" and then I copied the files to "Dev Pro 1" but as you can see the report makes it _appear_ as if files were copied to production when in fact they were copied from Beta to Dev Pro 1 _while_ Production was the active project.
![image](https://cloud.githubusercontent.com/assets/1228550/15437477/22460fd8-1e7c-11e6-96f7-458e619832ed.png)
- Can we also have the context menu on the open file as well (not just in the sidebar), and can it work with a command/hotkey
![image](https://cloud.githubusercontent.com/assets/1228550/15437587/cde65b04-1e7c-11e6-958c-416f1b64377d.png)
- Lastly, if by accident after selecting "Copy Files to Project" you select the same project that you were copying from it overwrites the file with an empty file :-1: 

Hope that helps, this is a great addition though, was very excited to pull it down.

**Comment by xjsender** [comment]
@Xtremefaith ,  
Point 1, I can't replicate your first point. 
Point 2, I think you can add it by yourself, I think this feature is just developed for you, however, I will add a command in the command palette.
Point 3, it's a bug, I will fix it.

Thanks.

**Comment by Xtremefaith** [comment]
How would I accomplish #2? 

Also 3 other teammates experience the same issue with #1. It's a clerical bug not a functional one. Meaning the file goes to the correct place but the text says it went to the wrong place.

Thanks again

**Comment by xjsender** [comment]
@Xtremefaith , your point 1 and point 3 are bugs and fixed already by the latest commit.

About point 2, I need to add a context command to do it.

**Comment by xjsender** [comment]
@Xtremefaith , add a new context command ``copy_file_to_project``, you can bind your key mapping to this command by yourself.

**Comment by xjsender** [comment]
@Xtremefaith , if the new command can solve your problem, please help me close this issue.

**Comment by Xtremefaith** [comment]
Point 2 works fine, I added a key binding with that command and worked as expected. You mentioned point 3 was a bug that was squashed but I still do not see it in my context menu when I right click within an open file. Here is another screenshot to show what I am currently seeing in v3.4.2

![image](https://cloud.githubusercontent.com/assets/1228550/15520451/6341ead8-21bb-11e6-8d1a-192d0a04738c.png)

**Comment by xjsender** [comment]
@Xtremefaith , as I said before, I will not add a context menu for this feature because the performance problem of context menu is not good and the ``copy_file_to_project`` feature is not frequently used by other people.

I think you can use the keymap to copy file to other project and no need to do it by context menu.

Thanks

**Comment by Xtremefaith** [comment]
Sorry I didn't realize what you were saying at the time, thank you this works great and honestly as a hotkey person I will likely just use that now that I got it working. Thank you again, awesome job!

**Comment by Xtremefaith** [comment]
Is it possible to also have the meta file migrated with it if it exist?

**Comment by xjsender** [comment]
I already did.

发自我的 iPhone

**Comment by Xtremefaith** [comment]
Ya I found it it was my fault and I withdrew my comment
