### ISSUE TITLE
Diff with server changes active project

### ISSUE THREAD

**Issue by reyesml** [xjsender/haoide#117]
I have production and sandbox salesforce orgs.  If sandbox is my active project, and I diff a sandbox file with the production server, the active project switches to production and I get this error message from haoide:

-------------------------------------------------------------------------------
                   errorCode: 	NOT_FOUND                     	
                     message: 	The requested resource does not exist	
                  Time Stamp: 	2016-05-25 11:54:38           	
-------------------------------------------------------------------------------

If I leave production as the active project, and diff the sandbox file with production again, then the diff works fine.

I'm running Haoide v3.4.1 in SublimeText 3103.  This issue first appeared in haoide v3.4.0

**Comment by reyesml** [comment]
Thanks for the fix!  It works great in v3.4.3.

**Comment by xjsender** [comment]
You are welcome. Thanks for your report for this issue.
