### ISSUE TITLE
logs from server: please add the ability to see only my debug without anything else

### ISSUE THREAD

**Issue by vitaly-zdanevich** [xjsender/haoide#119]

**Comment by xjsender** [comment]
@vitaly-zdanevich , you can use ``Fetch Self`` command to list all debug logs for yourself.

**Comment by vitaly-zdanevich** [comment]
I mean to see only output of my **System.debug()**

**Comment by xjsender** [comment]
@vitaly-zdanevich , understood.

**Comment by KalGos** [comment]
What's the solution? Please map it to here if it is already solved/delivered.

**Comment by xjsender** [comment]
@KalGos there is a command named ``view_debug_only``, please check [here](https://github.com/xjsender/haoide/blob/master/config/keymap/Default%20(Windows).sublime-keymap#L116),

**Comment by KalGos** [comment]
Thanks @xjsender . But can't select the option as it's disabled. Any idea? I can do the 'debug only' from the Dev console.
