### ISSUE TITLE
使用HaoIDE下载salesforce工程只有目录没有文件

### ISSUE THREAD

**Issue by blazejurn** [xjsender/haoide#12]
sublime版本号：sublime text build 3047
版本号：Dev Channel, Build v2.7.9
通过HaoIDE下载salesforce工程，下载的新版本后，只有目录，没有文件了。
![image](https://cloud.githubusercontent.com/assets/10443066/6141034/c8a0ffe2-b1da-11e4-8651-9da1c00bab1e.png)

**Comment by xjsender** [comment]
Duplicate with #11
