### ISSUE TITLE
it is possible to edit code of custom button or link?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [xjsender/haoide#122]
I tried to toggle metdata objects **ActionLinkGroupTemplate** and **CustomPageWebLink** - and saw only new empty folders.

Also it is not a typo with word **metdata**? Maybe correct is **metadata**?

![screen shot 2016-06-10 at 9 31 40 am](https://cloud.githubusercontent.com/assets/3514015/15956117/ede3c27a-2eee-11e6-8af1-1c8b6cef0169.png)

**Comment by xjsender** [comment]
@vitaly-zdanevich , it metadata type is ``WebLink`` and it is included in ``Object.xml`` after retrieved from server.

**Comment by vitaly-zdanevich** [comment]
Hm, I do not understand you. In list of Metdata objects I not see **WebLink** but see **CustomPageWebLink**, ok I enabled **CustomPageWebLink** - and now I see new empty folder **weblinks** without any **Object.xml** in my workspace

**Comment by xjsender** [comment]
@vitaly-zdanevich ,  Yes, you are right, ``WebLink`` is the child metadata object of ``Object``, I just list out all of parent metadata, you just need to choose the ``CustomObject``, the button or links will be contained in the ``Object.xml``.

**Comment by vitaly-zdanevich** [comment]
ok, now I see my js for custom button, but instead of " I see `&quot`;

![screen shot 2016-06-10 at 3 22 48 pm](https://cloud.githubusercontent.com/assets/3514015/15964062/439bc778-2f1f-11e6-8ddb-171dea676e4e.png)

**Comment by xjsender** [comment]
yes，that's why it is not convenient to edit button in sublime.
