### ISSUE TITLE
field for new file covered by status bar

### ISSUE THREAD

**Issue by vitaly-zdanevich** [xjsender/haoide#123]
![screen shot 2016-06-10 at 3 20 00 pm](https://cloud.githubusercontent.com/assets/3514015/15964112/8ad3ab74-2f1f-11e6-8ca0-18f35c606243.png)

Version of Sublime Text: 3103; Mac

**Comment by xjsender** [comment]
@vitaly-zdanevich , you just need to drag and magnify the input panel as below picture, by the way, this is the problem of sublime and can't control by ``haoide``

![image](https://cloud.githubusercontent.com/assets/1450977/15982591/f187b89e-2fbd-11e6-9b5a-cd79422a1751.png)
