### ISSUE TITLE
This component is not in active project after creating new class 

### ISSUE THREAD

**Issue by weivreca** [xjsender/haoide#125]
When I create a new class and hit ctrl-alt-s I get "This component is not in active project after creating new class". It used to work but now I have to deploy to server first and then ctrl-alt-s works

**Comment by xjsender** [comment]
Whats your plugin version? If not latest, please try to upgrade to latest version and try it again.

I think its a old issue met before.

**Comment by weivreca** [comment]
Thanks, 3.4.0 seems to have fixed it. Thanks again
