### ISSUE TITLE
Please use TLS 1.1 or higher when connecting to Salesforce using https.

### ISSUE THREAD

**Issue by fenixjke** [xjsender/haoide#127]
Hi,
I have an issue that haoide cannot connect to production (HaoIDE -> Switch Project, for example) and provide next error message:
"TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https."
What can I do in HaoIDE setting to solve this problem?

**Comment by xjsender** [comment]
no solution so far

**Comment by eugene-vabishchevich** [comment]
it's critical issue

**Comment by xjsender** [comment]
@fenixjke , @eugene-vabishchevich , I know it's a critical issue, I will try to fix it from tonight.

**Comment by eugenevabishchevich** [comment]
@xjsender please fix it. Mavensmate is a pain :)

**Comment by eugene-vabishchevich** [comment]
Hi guys! Just install Sublime 3117 from developer space: https://www.sublimetext.com/3dev

It should help.

**Comment by SunLangzi** [comment]
window的可以使用，但mac的昨天出现该问题

**Comment by xjsender** [comment]
@eugene-vabishchevich , I tried to replicate this issue in four sandboxes but I can't.

My enviroment:
---
* My OS: OSX EI Captian 10.11.5
* Sublime: 3114

What about yours?

**Comment by eugene-vabishchevich** [comment]
@xjsender 
The issue was in 3103 because Haoide plugin didn't work in 3114. But I installed 3117 and it works.

**Comment by xjsender** [comment]
@eugene-vabishchevich , sublime 3117 is not stable version, I don't recommend you install this verison.

Actually, haoide can work with sublime 3114, you just need to make some change on sublime core code ``sublime_plugin.py`` according to issue #112.

**Comment by xjsender** [comment]
I paste the solution to here, check below:
---
In your main Sublime Text folder there's a `sublime_plugin.py` file. All you have to do is change the line 728 from:
```python
print(f, "in", zippath, "is not utf-8 encoded, unable to load plugin")
```
to
```python
print(f, "in", self.zippath, "is not utf-8 encoded, unable to load plugin")
```

**Comment by eugene-vabishchevich** [comment]
@xjsender it works, thanks!

**Comment by ashishcloud** [comment]
I downloaded 3114 version but I haoide menu items are disabled now and I cant even find sublime_plugin.py file in my system. I am using mac air.

any thoughts ?

**Comment by xjsender** [comment]
Find the sublime.app in your finder, and then click the right mouse button, execute ``Show Package Content > Contents > MacOS > sublime_plugin.py``

**Comment by devaubs** [comment]
I have Build 3103 and I have successfully updated the sublime_plugin.py file, but I'm still getting the "TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https." error when switching to my sandbox project. Should I download a different build of Sublime?

**Comment by xjsender** [comment]
@devaubs , you should upgrade your sublime so that TLS1.1 problem would be fixed.
