### ISSUE TITLE
TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https

### ISSUE THREAD

**Issue by ForceComDeveloper** [xjsender/haoide#130]
Hello,

I have this error since yesterday : 
TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https.

Whatever I do I get this message (update, retrieve)

What should I do ?

**Comment by xjsender** [comment]
@ForceComDeveloper , did you check the issue #127 ?

**Comment by ForceComDeveloper** [comment]
Sorry did not see that before. Thanks
