### ISSUE TITLE
Upgrade to API version 37 and api version option on project level

### ISSUE THREAD

**Issue by Shababsoft** [xjsender/haoide#132]
Hello @xjsender, 

Is it possible that you can update the default API version from 35 to 36 or 37? 
Please can you also provide `api_version` option under project level as well. so I can choose different api versions for projects.

**Comment by xjsender** [comment]
@Shababsoft , I will add this feature to next release.

**Comment by Shababsoft** [comment]
@xjsender Any progress?

**Comment by xjsender** [comment]
@Shababsoft , too busy these days, sorry for that.

**Comment by Shababsoft** [comment]
@xjsender please can you provide the link of .sublime-package file because Package Controller package update is not working on windows 10. 

Please can you tell how do you create the '.sublime-package' file from the source.zip?

**Comment by xjsender** [comment]
@Shababsoft , I just upload the [haoide.sublime-package](https://github.com/xjsender/haoide/releases/download/v3.4.6/haoide.sublime-package) to release.
