### ISSUE TITLE
Allow to deploy destructiveChanges.xml

### ISSUE THREAD

**Issue by Shababsoft** [xjsender/haoide#133]
Can you provide option to deploy a folder that contains destructiveChanges.xml file, which allows to remove components in scr folder.

**Comment by xjsender** [comment]
@Shababsoft , you can directly destruct class or any other components by context command ``Destruct Package.xml From Server``, see below screenshot,

![image](https://cloud.githubusercontent.com/assets/1450977/16873965/13df13a8-4ac9-11e6-9d03-fc1274431413.png)

**Comment by xjsender** [comment]
@Shababsoft , Or you can choose files in the sidebar and then execute ``Destruct Files From Server`` command, above command is used to massive destruct files from server.

**Comment by xjsender** [comment]
Plugin also supports completion for ``package.xml`` building, just only need you to download metadata cache by ``Metadata > Reload Project Cache`` before build package.xml, please check [here](https://github.com/xjsender/haoide/blob/master/docs/completion.md#packagexml-completion) for more detail

**Comment by Shababsoft** [comment]
@xjsender  Thanks.. I wasn't aware of destruct package.xml option
