### ISSUE TITLE
Network connection timeout issue

### ISSUE THREAD

**Issue by mrpreddy** [xjsender/haoide#136]
Facing login issue. All menu items are disabled. please share the default settings. 

Error: Network connection timeout

**Comment by xjsender** [comment]
@mrpreddy , if all menu items are disabled, please check issue #112 , if solution for issue #112 can't fix your problem, please tell me your windows, sublime and haoide version, thanks.

**Comment by mrpreddy** [comment]
Windows 7
Sublime 3 build 3103
HaoIDE Build v3.4.5

**Comment by mrpreddy** [comment]
I have done the changes as given #112 and toolingapi.sublime-settings as given below,
{
"workspace" : "",
"projects" : { 
  "Project1":{
          "allowed_packages":
                 [
                 ],
          "default": true,
          "login_url": "https://login.salesforce.com",
          "password": "xxxxxx",
          "security_token": "vRNdnuTLLZsQAPWWszV1BG9Wv",
          "subscribed_metadata_objects":
               [
               ],
          "username": "mrpreddy@sabre.com"
     },
       "Project2":{
          "allowed_packages":
                 [
                 ],
          "default": false,
          "login_url": "https://login.salesforce.com",
          "password": "xxxxxx",
          "security_token": "vRNdnuTLLZsQAPWWszV1BG9Wv",
          "subscribed_metadata_objects":
               [
               ],
          "username": "mrpreddy@sabre.com"
     },
}
}

Please let me if i have missing something
FYI, I have tried sublime Build 3114 as well but it didn't worked.

**Comment by mrpreddy** [comment]
I want export all ..please let me know the process to  export roles, custom objects, custom fields, FLS,, validation rules, workflow rules etc . Currently export options are also grayed out.

**Comment by xjsender** [comment]
@mrpreddy , I wonder how do you get the ``Network connection timeout`` message when your all menu items are disabled.

**Comment by mrpreddy** [comment]
@xjsender , Its problem with the proxy. Worked well. Thanks you. I had an issue, while exporting profile, i got "Ã¢Ë†Å¡" value in the cells. is this is known functionality or anything need to done to remove it.

**Comment by mrpreddy** [comment]
![issue](https://cloud.githubusercontent.com/assets/1014297/17862006/02ef08c2-68b1-11e6-9296-883feafc5c68.JPG)

**Comment by xjsender** [comment]
@mrpreddy , you should convert it's encoding to utf-8 with text editor like Notepad++ or something else.
