### ISSUE TITLE
Deploy Package.zip RunSpecifiedTests Error

### ISSUE THREAD

**Issue by srozell4** [xjsender/haoide#138]
When I try to deploy using the Deploy Package.zip method, I get the error `INVALID_OPERATION: runTests must not be empty when a testLevel of RunSpecifiedTests is used`

Here are the deploy_options set in user settings: 
```
"deploy_options":
	{
		"allowMissingFiles": false,
		"autoUpdatePackage": false,
		"checkOnly": false,
		"ignoreWarnings": true,
		"performRetrieve": false,
		"purgeOnDelete": false,
		"rollbackOnError": true,
		"runTests": "AccountTest",
		"singlePackage": true,
		"testLevel": "RunSpecifiedTests"
	}
```

From a previous issue, It looks like I should get a prompt but that is not working. I resulted in right-click on file and Deploy to Server for now since the prompt works for that. But it would be nice to use this when deploying a package.

**Comment by xjsender** [comment]
@srozell4 , yes, it is a problem, I will add ``RunSpecifiedTests`` support for ``Deploy Zip`` command, thanks for you feedback.
