### ISSUE TITLE
Deployment Options Not Working - (related to Sublime Text 3124 release?)

### ISSUE THREAD

**Issue by KMBorg** [xjsender/haoide#141]
I think this may be related to the Sublime Text 3124 release today that I installed, but when I go to either right click and deploy a single file or deploy a package, it says "Deploying Metadata to Production", and then "Metadata Deployment Finished", but it's not actually deploying anything or running any tests. I'm not getting any other visible errors, and I checked the deployment status in the Salesforce GUI just to see if maybe it was deploying but not showing me the progress, but there isn't an entry for it there either.

**Comment by xjsender** [comment]
@KMBorg , please check issue #101 .

**Comment by KMBorg** [comment]
If I'm understanding your response to the other ticket correctly, I'm using version 3.4.5 and I tried removing the  deployment options I had added to my user settings like you suggested in #101, and it didn't have any effect. 

This is what my user settings file normally looks like (with sensitive information removed):

{
	"deploy_options" : {
        "allowMissingFiles" : false,
        "autoUpdatePackage" : false,
        "checkOnly" : false,
        "ignoreWarnings" : true,
        "performRetrieve" : false,
        "purgeOnDelete" : false,
        "rollbackOnError" : true,
        "singlePackage" : true,
        "testLevel": "RunLocalTests", 
        "runTests" : "true"
    },
	"keep_project_name_time_suffix": false,
	"projects":
	{
		"Production":
		{
			"allowed_packages":
			[
			],
			"default": true,
			"login_url": "https://login.salesforce.com",
			"password": "mypassword",
			"security_token": "mysecuritytoken",
			"subscribed_metadata_objects":
			[
				"ApexClass",
				"ApexComponent",
				"ApexPage",
				"ApexTrigger",
				"AppMenu",
				"AuthProvider",
				"ConnectedApp",
				"CustomApplication",
				"CustomApplicationComponent",
				"CustomLabels",
				"CustomObject",
				"CustomObjectTranslation",
				"CustomPageWebLink",
				"CustomPermission",
				"PermissionSet",
				"CustomSite",
				"CustomTab",
				"Dashboard",
				"Document",
				"EmailTemplate",
				"Group",
				"HomePageComponent",
				"HomePageLayout",
				"Layout",
				"Letterhead",
				"PostTemplate",
				"Profile",
				"Queue",
				"QuickAction",
				"RemoteSiteSetting",
				"Report",
				"ReportType",
				"Role",
				"SharingRules",
				"StaticResource",
				"Workflow",
				"Settings"
			],
			"username": "myusername@something.com"
		},
		"Sandbox":
		{
			"allowed_packages":
			[
			],
			"default": false,
			"login_url": "https://test.salesforce.com",
			"password": "mypassword",
			"security_token": "mysecuritytoken",
			"subscribed_metadata_objects":
			[
			],
			"username": "myusername@something.com"
		}
	},
	"workspace": "C:/Users/myUser/Dropbox/Salesforce"
}

**Comment by xjsender** [comment]
@KMBorg , I just tried to use your setting to deploy file to server but not replicate your issue.

Can you open your console by clicking``View > Show Console`` and check whether there has any exception there?

**Comment by KMBorg** [comment]
Figured it out. When I went to deploy, the following error message showed up in the console (see below), so I deleted my file session.json in my config folder, refreshed the classes folder in the project so it would recreate the session file, and now it works just fine.

Thanks for your help!! :)

INFO:haoide.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): login.salesforce.com
DEBUG:haoide.requests.packages.urllib3.connectionpool:"POST /services/Soap/u/v35.0 HTTP/1.1" 200 414
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 <soapenv:Body>
  <loginResponse xmlns="urn:partner.soap.sforce.com">
   <result>
    <passwordExpired>false</passwordExpired>
    <serverUrl>https://na14.salesforce.com/services/Soap/u/5.0/someId</serverUrl>
    <sessionId>somelongsessionId</sessionId>
    <userId>myUserId</userId>
   </result>
  </loginResponse>
 </soapenv:Body>
</soapenv:Envelope>
Exception in thread Thread-5:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "salesforce.api.metadata in C:\Users\myUser\AppData\Roaming\Sublime Text 3\Installed Packages\haoide.sublime-package", line 497, in deploy
  File "salesforce.api.metadata in C:\Users\myUser\AppData\Roaming\Sublime Text 3\Installed Packages\haoide.sublime-package", line 38, in login
  File "salesforce.login in C:\Users\myUser\AppData\Roaming\Sublime Text 3\Installed Packages\haoide.sublime-package", line 109, in soap_login
  File "util in C:\Users\myUser\AppData\Roaming\Sublime Text 3\Installed Packages\haoide.sublime-package", line 905, in add_config_history
PermissionError: [Errno 13] Permission denied: 'C:/Users/myUser/Dropbox/Salesforce/Production\\.config/session.json'

**Comment by xjsender** [comment]
@KMBorg , I also got this error a year ago but I can't replicate it again, maybe it's a issue related with OS.
