### ISSUE TITLE
Sync Test - HTTP Method 'GET' not allowed. Allowed are POST

### ISSUE THREAD

**Issue by Shababsoft** [xjsender/haoide#142]
@xjsender  I am getting the the following error message when trying to run a `Run Sync Test` or `Run Tests` commands in api version 37.0
`message: 	HTTP Method 'GET' not allowed. Allowed are POST`
`errorCode: 	METHOD_NOT_ALLOWED`

**Comment by xjsender** [comment]
@Shababsoft , this issue is replicated with issue #128 .

**Comment by Shababsoft** [comment]
@xjsender Sorry, I didn't notice

**Comment by xjsender** [comment]
@Shababsoft , no problem, thanks for your feedback.
