### ISSUE TITLE
Feature Request:  DeployOptions at the Org/Project level

### ISSUE THREAD

**Issue by DrByrnes** [xjsender/haoide#143]
It'd be really great if we could specify different DeployOptions for each project - that way we could deploy to production successfully (by running tests) and to sandbox environments quickly (without running tests).

Thoughts?

**Comment by xjsender** [comment]
Yes，you can already.

**Comment by DrByrnes** [comment]
Ah, I was unaware, thanks.  Is the entire 'deploy_options' setting just entered as a child node for each project?  (An example of the format would be great!)

**Comment by DrByrnes** [comment]
Never mind, I'm an idiot.  Didn't realize the settings-default example was already at that level.  

Kudos again to a great plugin, @xjsender - I use HaoIDE nonstop and always recommend it to my peers.

**Comment by xjsender** [comment]
@DrByrnes , thanks.
