### ISSUE TITLE
describe Sobject default syntax highlight

### ISSUE THREAD

**Issue by vitaly-zdanevich** [xjsender/haoide#145]
by default I see Java syntax that breaks after `'`:

![screen shot 2016-11-03 at 12 34 52](https://cloud.githubusercontent.com/assets/3514015/19961146/0363fb7e-a1c2-11e6-98ed-4d0ea0607ee4.png)

but `Textile` is better:

![screen shot 2016-11-03 at 12 35 01](https://cloud.githubusercontent.com/assets/3514015/19961164/15975ade-a1c2-11e6-964d-06f60e38b4a7.png)

**Comment by xjsender** [comment]
@vitaly-zdanevich , I will update the syntax as you wanted.

**Comment by vitaly-zdanevich** [comment]
@xjsender thank you!
