### ISSUE TITLE
Apex syntax highlight

### ISSUE THREAD

**Issue by pventurino** [xjsender/haoide#150]
Add Apex syntax highlight to the package.

Right now there's no syntax provided and HaoIDE defaults to `Java` syntax for `.cls` files. But this breaks the syntax coloring when initializing maps or sets.

MavensMate has a working Apex syntax, would be great to be able to use it without installing the full MavensMate package.

![screen shot 2017-03-02 at 3 21 33 pm](https://cloud.githubusercontent.com/assets/925320/23531639/40ea79f8-ff5c-11e6-95c5-c60bb518baef.png)

**Comment by rspurrell** [comment]
I've encountered this many times myself.  So, I agree, this would be a nice addition.

**Comment by lushang** [comment]
> Add Apex syntax highlight to the package.
> 
> Right now there's no syntax provided and HaoIDE defaults to `Java` syntax for `.cls` files. But this breaks the syntax coloring when initializing maps or sets.
> 
> MavensMate has a working Apex syntax, would be great to be able to use it without installing the full MavensMate package.
> 
> ![screen shot 2017-03-02 at 3 21 33 pm](https://cloud.githubusercontent.com/assets/925320/23531639/40ea79f8-ff5c-11e6-95c5-c60bb518baef.png)

Close this issue since the syntax highlight works as expected now (v.3.5.8)
