### ISSUE TITLE
View Lightning JS controller, helper, css, etc

### ISSUE THREAD

**Issue by eugene-vabishchevich** [xjsender/haoide#151]
Hello! 

Is that possible to view and edit internal items for lightning components after creation in haoide?

**Comment by pfronczak** [comment]
Lightning component bundles are by default created only with the Component (.cmp) file.
You can add controller, helper, css etc to the bundle by right-cklicking the bundle name in the side panel, then selecting HaoIDE -> Create Lightning Controller/Helper/etc

![image](https://cloud.githubusercontent.com/assets/1353027/25433917/7e5b1afa-2a8a-11e7-8a73-702a5e260d1c.png)

**Comment by xjsender** [comment]
@pfronczak  thanks for your reply.
