### ISSUE TITLE
Debug Log & Code Coverage

### ISSUE THREAD

**Issue by KalGos** [xjsender/haoide#152]
This may be a question: How to run a test and get the debug log and code coverage? Now I do a 2 step process. 
HaoIDE --> Run Sync Test (to get the Code coverage)
HaoIDE --> Run Test Class (to get the 'LogId', and the HaoIDE --> View Debug Log Detail)
Is there any easier step(s)? 

Why the 'View Debug Only' is disabled, when I selected the LogId?

**Comment by lushang** [comment]
For viewing the debug log, you have to run the test class and get the log in the newly test result by context menu, as you said.

For viewing code coverage, now you have two options:
1. From Test Result:
    - Open and run certain test class use command in context menu(`Ctrl+Alt+t`)
    - In the Test Result file, select the name of class/trigger and run context menu command `View Apex Code Coverage`
2. From Certain Apex class/trigger:
    - Open the Apex class/trigger you want view
    - View code coverage by context menu command `View Code Coverage`, make sure you have run related test class before.
