### ISSUE TITLE
Selected classes/pages for a project

### ISSUE THREAD

**Issue by KalGos** [xjsender/haoide#154]
Can I download a set of classes or pages without downloading all of the classes or pages for a project?

**Comment by xjsender** [comment]
Hi @KalGos , there is a feature named ``Refresh Package`` as described in the screenshot, which is used to download class or pages according to the package.xml in the specified folder, check the [QA](https://github.com/xjsender/haoide/blob/faa94af816377fb736c99a42e1394fffb3a2861e/README.md#qa) for that

![image](https://user-images.githubusercontent.com/1450977/28742840-5098e19c-746d-11e7-8842-8d7a33127be3.png)
