### ISSUE TITLE
Encrypt Salesforce passwords and security tokens

### ISSUE THREAD

**Issue by gabewonders** [xjsender/haoide#156]
Hello, is there any way to encrypt the Salesforce passwords and security tokens that are stored in the `toolingapi.sublime-settings` file? I don't like the idea of having several passwords/tokens store in plain text on my computer.

**Comment by xjsender** [comment]
Hi @gabewonders , I tried to figure out that, but I didn't a way to do that, can you give your suggestion for that?

**Comment by xjsender** [comment]
@gabewonders please check the #168 for oAuth2 login, which will meet your request.
