### ISSUE TITLE
DX Integration

### ISSUE THREAD

**Issue by Xtremefaith** [xjsender/haoide#157]
I know some people are currently in the [Salesforce DX](https://developer.salesforce.com/platform/dx) pilot (myself included), and this summer the beta should be official with GA to follow shortly after. With that said I'm curious if there is any intention of extending HaoIDE or even creating a separate version that will cooperate with the new structure. For example something as simple as creating new class now cannot be done because the metadata structure is completely different ([see example](https://github.com/forcedotcom/sfdx-dreamhouse)). 

I've never built a plugin and thought about attempting a basic version to start running Force CLI commands through ST, but since you have done a great job with this in the past I thought I should post here to see what your thoughts are.

Thanks!

**Comment by xjsender** [comment]
@Xtremefaith cli mode is too slow for compiling class or something else, I am trying to build a new haoide for vscode, please check ``https://github.com/xjsender/haoide-vscode``
