### ISSUE TITLE
Network connection timeout

### ISSUE THREAD

**Issue by VinceFINET** [xjsender/haoide#161]
Hi @xjsender ,

I saw a closed ticket with the same title but when I read it I can't find any solution to the problem...
(see ticket at https://github.com/xjsender/haoide/issues/136 issued by @mrpreddy)

So here is the context i'm using : 
- SublimeTest: Version 3.0 Build 3143
- Package Control: last version
- HaoIDE: Dev Channel, Build v3.4.7
- OS: Windows 7
- Internet proxy with username and password

I have the following configuration (i put "XXX" instead of real values of course):
```
{
  "workspace": "C:/CI/Workspace/",
  "projects": {
    "dev": {
      "default": "true",
      "login_url": "https://test.salesforce.com",
      "username": "vincent.finetXXXX@XXXXXXXXX",
      "password": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "security_token": "XXXXXXXXXXXXXXXXXXXXXXX",
      "workspace": "C:/CI/Workspace/dev"
    }
  }
}
```

When I select HaoIDE > New > New Project, nothing happens (all menus are still grey)
and in the console I have: 
> Copyright © 2013-2016 By Hao Liu, Dev Channel, Build v3.4.7
> 
> dev: 2017.09.27 11:37:27: Network connection timeout

Is it a proxy issue? where can i setup my proxy information if needed?

Thank you

**Comment by xjsender** [comment]
Hi 
@VinceFINET , Because I use the requests lib for http request, you can set proxy as [here](http://docs.python-requests.org/en/latest/user/advanced/#proxies)

**Comment by VinceFINET** [comment]
thank you @xjsender for that precision.
I understand that the export needs to be launch in the Python env of Sublime Text.

But where do i type/excecute the two exports?

Do I just open the Console and type the code:
export HTTP_PROXY="http://user:password@x.y.z.a:port"
export HTTPS_PROXY="http://user:password@x.y.z.a:port"

Or do I have to change your code?

Or something else?

Thank you in advance.
Vince

**Comment by xjsender** [comment]
@VinceFINET , just set the environment for your windows or Mac, you just know how to set environment.

**Comment by VinceFINET** [comment]
yooohhoooooooooo !!!!
so on windows i just added the environment variables HTTP_PROXY and HTTPS_PROXY.
i restarted sublime text and then it worked!!!!!

thank you so much.
