### ISSUE TITLE
Clean up right-click / context menus

### ISSUE THREAD

**Issue by DrByrnes** [xjsender/haoide#162]
While this is a relatively minor or cosmetic request, I think there's merit asking for it.

If I right-click on a file in a project I have the following options that are confusing:

- Diff with Server
- Retrieve from Server
- Deploy to Server
- Destruct from Server
-----------
- Diff with this Server
- Retrieve from this Server
- Deploy to this Server
-----------
- Refresh from Server
- Save to Server
- Delete from Server
-----------  (all the rest aren't applicable to this request so I'll ignore them...)

It seems like it would be more clear if these were organized into two groups - one for the tooling API and one for the other metadata API.  Perhaps something like:

[Metadata]
 - Diff with Server
 - Refresh from Server
 - Deploy to Server
 - Delete from Server
-----------------
[Tooling]
 - Diff with Server
 - Refresh from Server
 - Deploy to Server
 - Delete from Server

And I'd recommend each action prompts for the specific server, without a confirm/deny pop-up that currently exists.

Similar thoughts when right-clicking a file from the folder pane.  Current I see:

- Retrieve files from Server  
- Deploy files to Server
- Destruct files from Server
- Refresh files from Server  
- Delete files from Server

While I rarely use this particular menu, it seems like the last two are duplicates, but if they aren't, it isn't clear how they differentiate themselves.

Thoughts?

**Comment by xjsender** [comment]
@DrByrnes , Yes, you are right, I also think it's messy, maybe you can contribution to this, there is a [Context Menu](https://github.com/xjsender/haoide/blob/master/config/menus/Context.sublime-menu) to control the menu item in the code file, we can discuss on the detail.

**Comment by xjsender** [comment]
@DrByrnes what's your opinion?

**Comment by DrByrnes** [comment]
Assuming this doesn't require me to write any python I'm happy to assist....  ;-)

**Comment by xjsender** [comment]
@DrByrnes , you don't need to write code, just configuration for menu item.
