### ISSUE TITLE
Deploying a Visualforce Component also seems to deploy the associated Page

### ISSUE THREAD

**Issue by KnokkeLeZoute** [xjsender/haoide#163]
Hi all,

When I deploy a Visualforce component using "Save to server" or "Deploy to this server" options, it seems to also deploy the page(s) that refers to this component.

Do you have the same behavior ?
I'm using release 3.4.7

Kind Regards.

**Comment by xjsender** [comment]
@KnokkeLeZoute , when we deploy the component, we will deploy controller, helper, design and all others related the component to server.

**Comment by xjsender** [comment]
@KnokkeLeZoute , I didn't have the same behavior, did you double confirm that?

**Comment by KnokkeLeZoute** [comment]
Sorry, don't bother about it. I'll do some more testing and reopen the ticket if I get something more conclusive.
