### ISSUE TITLE
OAuth2

### ISSUE THREAD

**Issue by michacom** [xjsender/haoide#168]
First, Thanks for the great work!   👍 
After MM project has die, and I very love Sublime Text, and your plugin works really well, I'd like to switch to...

But until you implement OAuth2 login flow, it is forbidden to use it....      :`(

So, I'm waiting for this really needed feature.
Thanks.

**Comment by xjsender** [comment]
@michacom I am working on it. Got ideal from https://github.com/exiahuang/SalesforceXyTools.

**Comment by xjsender** [comment]
@michacom , it is just a beta version, I haven't finish test for all commands, if you want to try this feature, you can download the attached ``haoide.gz`` and renamed it to ``haoide.sublime-package``, and then put it to ``installed_packages``, after you install the new version, you just need to project as below:
```json
    "pro-sublime":
		{
			"default": true,
			"login_url": "https://login.salesforce.com",
			"security_token": "",
			"login_type": "REST",
			"subscribed_metadata_objects":
			[
				"ApexClass",
				"ApexComponent",
				"ApexTrigger",
				"AuraDefinitionBundle"
			],
			"username": "apex.sublime@dev.com"
		},
```
[haoide.gz package](https://github.com/xjsender/haoide/files/1686336/haoide.gz)

**Comment by xjsender** [comment]
@michacom  v3.5.2 is released, which includes oAuth2 login.
