### ISSUE TITLE
SOQL Query replaced in favor of Haoku Query

### ISSUE THREAD

**Issue by rspurrell** [xjsender/haoide#17]
Personally I preferred the old query style which returned JSON in the sublime window.  First the current implementation doesn't work. I keep getting the error "Error:INVALID_SESSION_ID: Session expired or invalid" even after authenticating through OAuth.  Second, I found it very convenient to immediately interact with the results in sublime, which I do often.

Please restore this feature to it's previous state or at least allow the user to choose which method they prefer! As they say "if it ain't broke don't fix it" :)

I miss being able to use CTRL + ALT + Q.  I've had to resort to using the dev console :(

Keep up the good work.

**Comment by xjsender** [comment]
@rspurrell , actually, you can always use it by [another way](https://github.com/xjsender/haoide#exceute-rest-test).

Choose any SOQL snippet and press ```ctrl+e``` in windows, and then press <kbd>q</kbd> and <kbd>Enter</kbd>, you will see the effect with original ```Execute SOQL```.
