### ISSUE TITLE
Export CSV is getting all blank files

### ISSUE THREAD

**Issue by amudduluru** [xjsender/haoide#176]
Export CSV is getting all blank files

**Comment by xjsender** [comment]
@amudduluru  what's your plugin version and OS version?

**Comment by amudduluru** [comment]
HI Hao,

I am using earlier version of 3.5.4.. Got updated today automatically.
OS = Windows 7.

Regards,
Ajay

**Comment by lushang** [comment]
This issue seems having been fixed in later version, issue closed.
