### ISSUE TITLE
FEATURE REQUEST: Deploy & Destruct at the same time

### ISSUE THREAD

**Issue by Xtremefaith** [xjsender/haoide#18]
Is there a way with HaoIDE to deploy a package with both new files AND destructing files?

Recently I made some major revisions to our codebase. I removed several utility classes from a previous developer that were integrated throughout the codebase. For example, we had a DataFactory.cls used for creating/inserting Sobjects. We had entries like this:

`DataFactory.createCustomerAccount();`

But now I've removed the DataFactory.cls and replaced all those entries with something like:

`Forge.insertSObject('Account');`

So in this small instance I would need to deploy Forge.cls along with any modified classes, and at the same time destruct DataFactory.cls (if I don't destruct it then it won't be covered by unit test any more and I'll fall below test coverage cause we're barely at 77% currently)

**Comment by xjsender** [comment]
@Xtremefaith 

#### You need to follow below six steps to finish this kind of job

* There is a ``file_exclude_patterns`` in the default settings, which is used to hide file in the sidebar, remove the ``"*.*-meta.xml"`` from it and paste this setting to your ``User Settings``
* After ```file_exclude_patterns``` is changed, click ``HaoIDE > Update > Update Project Pattern``, and then you will see the ``*-meta.xml`` files in the sidebar.
* If you want to delete a class or trigger, you just need to update the ``*.-meta.xml`` file as below,
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ApexTrigger xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>32.0</apiVersion>
    <status>deleted</status>
</ApexTrigger>
```
* Choose the file to delete, update or created into other org and click ```HaoIDE > Deploy Files To Server```
* After deploy is finished, you will see the result.
