### ISSUE TITLE
2018.07.05 15:11:29: UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 2042938781-44346 (1078131357)

### ISSUE THREAD

**Issue by Murthy-Tumuluri-CK** [xjsender/haoide#183]
Trying to create a project and i see below error

2018.07.05 15:11:29: UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 2042938781-44346 (1078131357)

**Comment by lushang** [comment]
It seems a exception from Salesforce.  Can you use `Ctrl+~` and paste messages in the control panel here?
