### ISSUE TITLE
Trivial Feature Request: Ability to hide an org from Switch Project (without deleting it from the settings file).

### ISSUE THREAD

**Issue by DrByrnes** [xjsender/haoide#188]
So I have a *lot* of orgs defined in my settings file, but I only typically use a few in any given week.  So to stop the large list from appearing when 'Switch Project' is selected I'd like to request that there be a flag added that indicates whether or not it appears.

Because, if I comment them out, as soon as the settings file is updated by toggling metadata objects, etc, the commented section is deleted entirely and I lose them.

A simple boolean property for each org, something like 'Hide_From_Switch_Project' or 'Hidden' or whatever makes sense.

A trivial request, I'm sure - but I'm guessing I'm not the only one that would benefit from it.

Thanks!

**Comment by xjsender** [comment]
@DrByrnes Yes

**Comment by xjsender** [comment]
We add a new setting ``hidden_in_project_list``, if you set this to ``false`` in your project, you will never find that when you switch project.

Check below sample.

```json
{
    "default": false,
    "hidden_in_project_list": true,
    "login_url": "https://logtestin.salesforce.com",
    "password": "xxxxxx",
    "subscribed_metadata_objects":
    [
        "ApexClass",
        "ApexPage",
        "ApexTrigger",
        "ApexComponent",
        "StaticResource"
    ],
    "username": "xxx@xxx.demo"
}
```
