### ISSUE TITLE
Feature Request: Update Project using custom Package.xml

### ISSUE THREAD

**Issue by Xtremefaith** [xjsender/haoide#19]
Currently if I build a custom `package.xml` inserting every EmailTemplate in our org because `<name>EmailTemplate</name>` [does not accept the * wildcard](https://www.salesforce.com/us/developer/docs/api_meta/Content/meta_emailtemplate.htm), the moment I use `HaoIDE > Update > Update Project (Alt+r)` it rebuilds the package.xml and I lose my edits. Also if I attempt to retrieve everything through `HoaIDE > Metadata Migration > Retrieve All (Alt+r, Alt+M)` it to rebuilds the `package.xml` removing my edits.

For now I've learned that I can open the `package.xml` and from the context menu use `HaoIDE > Retrieve Package.xml` which will get me the result I want but it creates a whole new folder that I then have to manually move the data back into my workspace respectively.

Can there be an option to retrieve the xml as I have built it and unpack it directly into my worspace the same way the other two options already do?

**Comment by xjsender** [comment]
@Xtremefaith , As-is, retrieved result of  ```package.xml``` will be extracted to the same path, so, what's you want is allowing you to input the extract path?

**Comment by Xtremefaith** [comment]
@xjsender I suppose you can word it that way. Essentially, right now the `package.xml` is in the src folder I don't want a `production[timestamp]` folder  to appear in my src file like it does now. I would rather it extract itself within the workspace like it appears to do with the `Update Project` and `Retrieve All` so I don't have to manually move the data myself.

Thanks

**Comment by xjsender** [comment]
@Xtremefaith , when you retreive the package, you can input the extract to path, is it ok for this issue?

**Comment by Xtremefaith** [comment]
How do I do that? You have an example?

**Comment by xjsender** [comment]
As I said, you can input the output path, just upgrade the plugin, retrieve a package.xml and you will see it.
