### ISSUE TITLE
Will this plugin available for create lightning web component?

### ISSUE THREAD

**Issue by ThisIszas** [xjsender/haoide#191]
As the lightning web component has become a new fashion. I think it's time to support lightning web component, since I think the visual studio code plugin is hard to use.

**Comment by lushang** [comment]
Yes, I will work on it.

**Comment by DrByrnes** [comment]
> Yes, I will work on it

Glad to hear it, @lushang!   Any idea when this might be ready or is it too early to guess?

**Comment by xjsender** [comment]
Delivered with basic feature, for example, lwc component completion, lwc creation, update or destruction.
