### ISSUE TITLE
salesforce/lib/dateutil/parser.py is not utf-8 encoded, unable to load plugin

### ISSUE THREAD

**Issue by BDeveau** [xjsender/haoide#192]
Using the current latest Sublime 3200, There is an error in the console during load stating parser.py is not utf-8 encoded and the plugin fails to load.

In fact, I am able to configure my projects, and "Switch Project" indicates a login success, however New->New Project fails, and all other "New" Options are disabled. The plugin does not seem to be functional.

**Comment by xjsender** [comment]
Already fixed by pull request, will be released in next version.
