### ISSUE TITLE
3.5.5 ignores 'switch_back_after_migration' on deploy

### ISSUE THREAD

**Issue by DrByrnes** [xjsender/haoide#195]
I just upgraded to the new 3.5.5 release and I noticed that deploying from one environment to another ignores the 'switch_back_after_migration' flag in the settings file as I'm left logged into the target environment as default.

Let me know if you need more details

**Comment by xjsender** [comment]
@DrByrnes , what did you deploy?

**Comment by xjsender** [comment]
@DrByrnes , what did you deploy?

**Comment by xjsender** [comment]
@DrByrnes ``ignore`` means you set it to false, is that correct?

**Comment by DrByrnes** [comment]
@xjsender  - I'm deploying an Apex class from my source environment (sandbox1) to my target environment (sandboxQA).  

The setting looks like this:  "switch_back_after_migration": true

After deploying, HaoIDE still tells me that I'm logged into my target environment (sandboxQA) instead of my source environment (sandbox1).

**Comment by xjsender** [comment]
@DrByrnes before you execute deploy operation, if your default project is ``sandboxQA``, you are trying to deploy class from ``sandbox1`` to ``sandboxQA``, your original project should be ``sandboxQA`` which is also the target environment to be deployed, maybe that's your question.

**Comment by DrByrnes** [comment]
@xjsender - All I noticed was that this is behaving differently that previous versions.  My active project would be sandbox1.  To deploy from sandbox1 to sandboxQA I'd then right-click and select 'Deploy to Server' and select sandboxQA.  

Prior versions would behave like so:  Deploy the open file to sandboxQA and then, upon completion of the deployment my active project would still be sandbox1.  

With 3.5.5 I repeat the exact same steps and my active project is now sandboxQA when deployment is completed.

Am I using this functionality incorrectly?

**Comment by xjsender** [comment]
If your active project is ``sandbox1`` and you are trying to deploy class in ``sandbox1`` to ``sandboxQA``, after deployment is finished, you active project should be ``sandbox``

If your active project is ``sandboxQA`` and you are trying to deploy class in ``sandbox1`` to ``sandboxQA``, after deployment is finished, you active project should be ``sandboxQA``

That's what I expected, it seems to be different with your expectation.

**Comment by DrByrnes** [comment]
> If your active project is `sandbox1` and you are trying to deploy class in `sandbox1` to `sandboxQA`, after deployment is finished, your active project should be `sandbox1`

Agreed, and it's not.  It's `sandboxQA`.

**Comment by DrByrnes** [comment]
@xjsender  - Okay, after a reboot and a thorough retest, this appears to be a non-issue, sorry!  I suppose I should have done that first just to be certain.
