### ISSUE TITLE
v3.5.6 - Export Profile creating 4 blank files

### ISSUE THREAD

**Issue by bellascratch** [xjsender/haoide#198]
Export works properly except for profiles. 4 files are produced with only the headers.

**Comment by lushang** [comment]
due to the csv file format simplification, reversed to the old version now.

**Comment by lushang** [comment]
Current version works fine under Windows and Linux (Ubuntu), OSX still has the issue.

**Comment by lushang** [comment]
> Current version works fine under Windows and Linux (Ubuntu), OSX still has the issue.

OSX version works fine after reload sublime text. the issue will be closed
