### ISSUE TITLE
After updates the code visualization is lost

### ISSUE THREAD

**Issue by fricco** [xjsender/haoide#2]
For some reason, after some weeks without opening Sublime, and after getting the last updates, the code visualization is lost, and now every class is opened as TeX and page as Plan Text

**Comment by xjsender** [comment]
@fricco , did your plugin update succeed and what's the version number?

**Comment by fricco** [comment]
It seems that it was not properly updated. Today I opened again an the 2.7.7 was downloaded and now it seems to be working fine again.
Thank you.
