### ISSUE TITLE
FEATURE REQUEST: Multiple Environments per workspace

### ISSUE THREAD

**Issue by Xtremefaith** [xjsender/haoide#20]
I'm wondering if its possible to have two environments on one project. For example I currently have Production and Sandbox projects which means I have to have 2 separate folders. So I either have to make a third folder for my git repository OR I put it in production/sandbox. Now whenever I make changes locally (like adding a new class), I have to copy it to the other folder which gets really annoying.

I would rather have one project folder called "Company Name" and then have 2 environment available to it. Switching just like I do now, or even selecting the environment when I retrieve/deploy. 

Thanks so much, still loving this plugin, surprised more people don't use it.

**Comment by xjsender** [comment]
@Xtremefaith , it's possible but I can't do it like that, because projects is always a user settings, If I did this, the projects in user settings must be updated as new format, however, I can't control the user settings.

**Comment by xjsender** [comment]
@Xtremefaith , If I add a new setting named ``company`` for project, can it solve your problem?

**Comment by xjsender** [comment]
@Xtremefaith, any response?
