### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by yuranun** [xjsender/haoide#200]
My pc use sublime + hao. I try to create new project after login. There is allow access after I click allow it's show 500 internal server error. It's occur only on my pc but my laptop is good. Please help me.

**Comment by lushang** [comment]
Can you provide more information about the 500 internal server error like screenshot, panel output (you can use `ctrl + \`` to display the panel)

Also check your network environment like WiFi, Ethernet link, proxy etc.

**Comment by yuranun** [comment]
it's show as below.

![image](https://user-images.githubusercontent.com/62602587/77525122-18121780-6ebb-11ea-9f6e-dc088d3bccb5.png)

![image](https://user-images.githubusercontent.com/62602587/77525213-3bd55d80-6ebb-11ea-9d19-0d881a4b1f9a.png)

**Comment by lushang** [comment]
Have you checked with your network environment like WiFi, Ethernet link, proxy  and also firewall, socket port settings? I can't recur nor figure out the problem.

**Comment by lushang** [comment]
Close the issue due to non-response for a long time.
