### ISSUE TITLE
After updating to the latest version in sublime, the code  current extension as don't has apex....

### ISSUE THREAD

**Issue by Jeff-Mingzhi** [xjsender/haoide#204]
![image](https://user-images.githubusercontent.com/51068225/77825250-0642a580-7143-11ea-85cd-f9f01f4c512a.png)
After updating to the latest version in sublime, the code  current extension as don't has apex....

**Comment by lushang** [comment]
We use sublime text standard Java highlight for Apex class/trigger and DO NOT Implement any custom syntax highlight for Apex class/trigger. 

Sine the sublime text standard Java highlight for Apex class/trigger works quite well currently, we have no plan for implementing a custom one.

**Comment by Jeff-Mingzhi** [comment]
> We use sublime text standard Java highlight for Apex class/trigger and DO NOT Implement any custom syntax highlight for Apex class/trigger.
> 
> Sine the sublime text standard Java highlight for Apex class/trigger works quite well currently, we have no plan for implementing a custom one.

it is my sublime problem,Thank you for your assistance.Best regards.
