### ISSUE TITLE
can't create project and retrieve data,always only get this folder

### ISSUE THREAD

**Issue by ZengZhenfei** [xjsender/haoide#208]
![image](https://user-images.githubusercontent.com/29648356/78087633-48464280-73f4-11ea-9e6b-4d7ee2eebf77.png)

**Comment by lushang** [comment]
Can you provide your related user settings and sublime console log (by pressing `Ctrl + ~` to display it) ?

**Comment by lushang** [comment]
Close the issue due to non-response for long time.
