### ISSUE TITLE
Minor:  New releases not updating version number

### ISSUE THREAD

**Issue by DrByrnes** [xjsender/haoide#209]
This is minor, but after upgrading to the recently released versions I'm unable to confirm what version I'm actually running.

When I press CTRL+1 to display the log, I still see:
`Copyright © 2013-2020 By Hao Liu, Dev Channel, Build v3.5.6`
Which is wrong as i know I'm running the current version, not 3.5.6.

Same with the menu popup displayed via:  
   HaoIDE --> About

That also says version 3.5.6.

**Comment by lushang** [comment]
The current version is v3.6.0

You may check if you have any custom channels for Package Control, by pressing `Perferences` -> `Package Settings` -> `Package Control` -> `Settings - User`. There was a case for that.

**Comment by lushang** [comment]
Close the issue due to non-response
