### ISSUE TITLE
Annonymous Apex don't have logs and the status bar do not show when executing

### ISSUE THREAD

**Issue by jerryzhen11** [xjsender/haoide#214]
Originally there are logs after the execution of the annonymous Apex code.
But now it disappeared.

And the status bar at the bottom do not show "executing" when we execute  annonymous Apex code.

**Comment by 402332509** [comment]
same issue after upgrading the package to 

Copyright © 2013-2019 By Hao Liu @ 2013-2019, Lushang @ 2020-2021
Dev Channel, Build v3.6.1

**Comment by lushang** [comment]
some user reported the issue, they fixed it by **restart Sublime Text 3**.

If this method does not work for you. Please update your problem with the [Raise an issue][1] format for better detection

[1]:https://github.com/xjsender/haoide/blob/master/docs/issue.md

**Comment by jerryzhen11** [comment]
Yes. It worked by restarting sublime.
Thanks.
