### ISSUE TITLE
After recent update (v2.9.0), switch project command returns '[ERROR] Invalid username, password, security token; or user locked out' for all orgs.

### ISSUE THREAD

**Issue by sattar786** [xjsender/haoide#24]

**Comment by xjsender** [comment]
it's a issue, you need to correct the credentials of current project.

**Comment by sattar786** [comment]
Thanks! for quick reply. I did managed to resolve it but the issue was not with credentials. While struggling with log-in; I manually edited the user settings and changed the default project by setting 'default=false' for previous one and 'default=true' for my target project. And, it worked perfectly.

After this, I am now able to switch between projects.

Thanks again for making HaoIDE!

**Comment by xjsender** [comment]
@sattar786 , thanks for your quick solution on this bug, I will fix it in the next release, which will be released tonight.
