### ISSUE TITLE
High RAM usage and slowness on deploying

### ISSUE THREAD

**Issue by ecastillo550** [xjsender/haoide#26]
Since the new updates I have been experiencing problems with a high RAM usage and slow response using the plugin. 
![haoide problem](https://cloud.githubusercontent.com/assets/2823009/7483864/488d247a-f348-11e4-8c53-13ec43b88b9a.png)

**Comment by xjsender** [comment]
@ecastillo550 , I checked the new update, I didn't make any change on ``deploy`` feature, I expericed the same problem yestoday, however, after I force quit sublime text, this problem can't be replicated again. 

I just tried the latest version of this plugin in ``Windows 7`` and ``Sublime 3065`` but still not replicate it.

My OS is ``OSX 10.10.3`` and ST version is ``Sublime 3083``, what's your ST Version? Can you replicate it again?

**Comment by ecastillo550** [comment]
I have Sublime Build 3083 on Windows 8.1. I forced quit three times and I am still having issues with the slow response. I will try to see what is happening.

**Comment by xjsender** [comment]
See https://www.sublimetext.com/forum/viewtopic.php?f=2&t=17866, change log of sublime 3083 said it fixed the high CPU crash problem, but it seems not.

I think you can try ``Sublime 3065`` to see what will happen.

**Comment by ecastillo550** [comment]
I got 3083 since it came out, weeks ago, ha have not had the problem since today, but I will give it a try to downgrade.

**Comment by Xtremefaith** [comment]
I have the same issue on v2.9.1 and ST 3083 on Windows 7 Enterprise, started last week some time, not sure what changed, but I open and close this everyday and it hasn't gone away since starting last week. 

For me it was not just deployment, it had something to do with the project itself. If I opened ST in a different project then I had no issues, but in my Salesforce project I had issues. I then began new and re-added my project folders from scratch and it seemed to be better for a time, but then again today during deployment I had the same issue all over again.

**Comment by xjsender** [comment]
@Xtremefaith , I am trying on on v2.9.1 and ST 3083 on Windows 7 Enterprise, thanks for your response.

**Comment by xjsender** [comment]
@ecastillo550 ， @Xtremefaith , I tried in the whole today but crash didn't happen.

**Comment by xjsender** [comment]
@ecastillo550 , @Xtremefaith , I checked with my friends who are using this plugin, most of them are using ``Sublime 3065`` or ``Sublime 3059`` and latest plugin version, however, their sublime is very stable and not crash like yours.

**Comment by ecastillo550** [comment]
I got It working right deleting everything about the workspace/project I used. I will still look around a little bit.

**Comment by xjsender** [comment]
@ecastillo550 , @Xtremefaith , did your sublime still in problem?

**Comment by ecastillo550** [comment]
@xjsender :I have not had a problem since then,, weird situation haha
