### ISSUE TITLE
New Project command (Ctrl+Alt+N) is not working.

### ISSUE THREAD

**Issue by sattar786** [xjsender/haoide#28]
After 2.9.2 update New Project command (Ctrl+Alt+N) is not working. It shows attached dialog.

To reproduce:
1.  Click on Switch Project (Alt+S)
2.  Click on New Project command (Ctrl+Alt+N)
![new_project_error](https://cloud.githubusercontent.com/assets/3061974/7560628/55cc047c-f7de-11e4-9a42-b63c4acd0aad.png)

**Comment by xjsender** [comment]
@sattar786 , you must subscribe one metadata object at least when you create new project, after you subscribed in this time, you will never see this screen after this time, a new ``subscribed_metadata_objects`` settings will kept to your project.

**Comment by xjsender** [comment]
@sattar786 , what you subscribed are the component types which will be downloaded to your project path. Generally, you should choose ``ApexClass``, ``ApexPage``, ``ApexTrigger``, ``ApexComonent`` and ``ApexPage``.

If you want to change the default subscribed component types, you can click ``HaoIDE > Settings > Toggle Metadata Objects`` to change it.

Sorry about the problem, I attach the notes in the release notes, however, I put the wrong path to display the release message.

**Comment by xjsender** [comment]
@sattar786 , see [this demo](https://github.com/xjsender/SublimeApexScreenshot/blob/master/BuildPackageXMLWithQuickPanel.gif) to for more information.

**Comment by xjsender** [comment]
@sattar786 , BTW, you should upgrade plugin to release 2.9.3, which has some hot fix on the new ``build_package_xml`` feature in the previous demo.

**Comment by xjsender** [comment]
@sattar786 , did it solve your problem?

**Comment by sattar786** [comment]
@xjsender -- You rock!. It is working now. Thanks!
