### ISSUE TITLE
Not bugs - just two requests

### ISSUE THREAD

**Issue by DrByrnes** [xjsender/haoide#3]
1.  After executing 'Deploy to Server' can HaoIDE automatically switch the user back to the source project?  Or, have a setting that can control this behavior to automatically switch back or not?

2.  How about a new feature titled something like 'Refresh from Other Project' that would prompt the user to select a non-active project and refresh that particular class/page/file from the chosen org/project.  Would be helpful, I think.

**Comment by xjsender** [comment]
@DrByrnes , these two features will be delivered in the next release.

**Comment by xjsender** [comment]
see [Description](https://github.com/xjsender/haoide#deploy)

**Comment by DrByrnes** [comment]
Glorious!  I used both of these features today and they're great.  Thanks, and nice work!

**Comment by xjsender** [comment]
@DrByrnes , you are welcome to submit more feature request.
