### ISSUE TITLE
metadataObjects doesn't work 

### ISSUE THREAD

**Issue by eugene-vabishchevich** [xjsender/haoide#30]
I have metadataObjects global settings with all objects that I need. This setting doesn't work. I need to New Project and subscribe locally. I need this GLOBAL setting for all my projects.

**Comment by xjsender** [comment]
@eugene-vabishchevich , since release 2.9.3, ``the subscribed_metadata_objects`` are kept in every project. 

if you want to change the default subscribed component types, you can click HaoIDE > Settings > Toggle Metadata Objects to change it.

**Comment by xjsender** [comment]
@eugene-vabishchevich , the original design is wrong one, every org has it's own specified ``metadataObjects``, as you know, when you create the project, plugin will ``describe_metadata`` to retrieve the ``metadataObjects`` from server but not hard copy on the plugin settings.

**Comment by eugene-vabishchevich** [comment]
@xjsender 
ok, got it. Do we need to remove metadataObjects from settings?

**Comment by xjsender** [comment]
yes. it's better to remove it, however, it's not required.
