### ISSUE TITLE
Deploy to Server doesn't work for inactive server

### ISSUE THREAD

**Issue by pfronczak** [xjsender/haoide#33]
"Deploy to Server" option doesn't work anymore when other than current (active) project is selected as a target for deployment. Selecting target server switches the active project but does not run the deployment.

I believe this stopped working some time around introducing changes with automatic opening of sublime projects when switching active project.

**Comment by DrByrnes** [comment]
@pfronczak , make sure the inactive project is properly subscribing to the metadata objects.  Switch to the target project, cache --> clear session cache, then settings --> toggle metadata objects.  (Do this twice.  The first time it'll pull down the list, the second it'll prompt you to choose.)  Once you've subscribed and refreshed that project you should have no problem deploying to it from another active project.  (I used this feature multiple times yesterday and it worked perfectly once all my projects were properly configured for the new metadata change.)

**Comment by pfronczak** [comment]
Thank you - that did solve the problem. I never used this feature (toggle metadata) before - I was just creating package.xml's and refreshing projects.
Deploy to server indeed works if the target project is subscribed to metadata objects.

**Comment by xjsender** [comment]
@DrByrnes , thanks for your response for @pfronczak .

**Comment by DrByrnes** [comment]
My pleasure, @xjsender !

**Comment by xjsender** [comment]
@pfronczak , @DrByrnes , this is a bug, it will happen when target deployment org didn't describe_metadata.

**Comment by xjsender** [comment]
This issue is fixed in the release 2.9.6
