### ISSUE TITLE
Can't decompress .gzip file when creating new project

### ISSUE THREAD

**Issue by xiaoenmali100** [xjsender/haoide#4]
On 2015/2/1, when I create a new project, it finally throws an en error:  Received response with content-encoding: gzip, but failed to decode it.
But on 2015/2/2, it works.
![issue1](https://cloud.githubusercontent.com/assets/10803281/5995023/5b2fff90-aac2-11e4-9ccd-0ed456d6ae84.jpg)

**Comment by xjsender** [comment]
see kennethreitz/requests#1944, I will upgrade this dependency lib to latest, which will fix this issue.
