### ISSUE TITLE
build package enhancement

### ISSUE THREAD

**Issue by tcoolma** [xjsender/haoide#47]
![image](https://cloud.githubusercontent.com/assets/5362195/8369416/e1d4eb7e-1beb-11e5-8d53-94968a11d4bd.png)

it should be better if we can select all searched components when Building package

**Comment by tcoolma** [comment]
Sharing rule for custom object is available now, please also include them in the package
![image](https://cloud.githubusercontent.com/assets/5362195/8371877/156404a6-1c10-11e5-84f0-f31d01185620.png)

**Comment by xjsender** [comment]
@tcoolma , the first one is not deliverable, however, the second one can be.

Can you please split this issue to two issues, thanks.
