### ISSUE TITLE
Operation keeps trying and block user

### ISSUE THREAD

**Issue by pipunx** [xjsender/haoide#48]
Sometimes my IP changes when i working on a existent session and the ide nor checks or warning about loggin problems and try to execute the command anyway. This leads to block my user, and even when that ocurrs the ide keeps trying endlessly without any message.

**Comment by xjsender** [comment]
@pipunx , this plugin will try to login util repeat_times reach 12, the timeout minutes of every time is 10 seconds, you can check the login module at [here](https://github.com/xjsender/haoide/blob/master/salesforce/login.py)

Actually, if you set ``debug_mode`` to ``true``, you will see the login exception in the console when login failed, do you want to add a settings to control the login repeat times?
