### ISSUE TITLE
SF Account is locked on update project when new session cannot receive

### ISSUE THREAD

**Issue by maksimln** [xjsender/haoide#49]
1. Create project with correct account data (username and password)
2. Edit password (eg. after expired password and forgot edit in user setting in sublime text)
3. Try to update package

http://monosnap.com/image/awOr5oZHLsK1hbFql80Rr8w31GnnOv

**Comment by maksimln** [comment]
Also update process never stop
Only throw killing sublime text

I think need try to get new session 2 times no more

Thanks.

**Comment by xjsender** [comment]
@maksimln , did you use the latest plugin version?

**Comment by xjsender** [comment]
@maksimln , I remember I have fixed this issue before, just now, I try to reproduce your problem but I can't reproduce it.

**Comment by xjsender** [comment]
@maksimln , I found the root cause, it's a issue, thanks for your report. 

Actually, you can execute ``HaoIDE > Cache > Clear Session Cache`` command to fix it.

**Comment by maksimln** [comment]
Now I use: Dev Channel, Build v3.0.9

**Comment by xjsender** [comment]
@maksimln , I just released a new version, can you help me double confirm whether new version fixed this issue?

**Comment by maksimln** [comment]
v3.1.0 - not reproduced in by case 

Thanks,
