### ISSUE TITLE
Repeated unsuccessful login

### ISSUE THREAD

**Issue by igoode** [xjsender/haoide#5]
Raised this issue a while ago but couldn't reproduce it ... now I can!

Switch Project -> org with expired password, happened to be a production org but not sure if that is relevant, then Update -> Update Project

See screenshot, repeated unsuccessful login attempts, only way to halt is to close and reopen Sublime.

![image](https://cloud.githubusercontent.com/assets/5027135/5995694/fc599788-aae9-11e4-9684-ff485396f174.png)

**Comment by xjsender** [comment]
@igoode , I just ran into this issue yesterday and fixed it. thanks for your response. 

This issue will be fixed in next release.
