### ISSUE TITLE
Visualforce page editing becomes slow on Windows

### ISSUE THREAD

**Issue by Shababsoft** [xjsender/haoide#51]
There is a delay while editing on the Visualforce pages since last update. When I disable the HaoIDE plugin everything works fine. Please can you have a look at the issue?

**Comment by xjsender** [comment]
@Shababsoft ， delay on what operation? Delay when you input word or just save?

**Comment by xjsender** [comment]
@Shababsoft , when you input chars just like ``.<: =#"`` in visualforce page, plugin will find the proper completions for your, did it delay when you input these chars?

**Comment by Shababsoft** [comment]
Yes... I am facing delay with the above characters and any html text I type on the page.

**Comment by xjsender** [comment]
@Shababsoft , your page is very large which contains lots of statement?

**Comment by Shababsoft** [comment]
No. the page has only 10 lines. This is happening since last update. I am using Windows 8.1, I am not sure whether it is only happening with me or all windows users.

**Comment by xjsender** [comment]
I think you can try different version of sublime.

**Comment by Shababsoft** [comment]
I have latest version of sublime text 3. your application was working perfect few days ago. I am facing this issue since last update. Did you test on a windows machine?

**Comment by xjsender** [comment]
@Shababsoft , I always use my mac for plugin develop and use my windows for daily working, everything is ok with my windows computer.

## My windows configuration: 
* Windows 7 64bit, i5 CPU
* Sublime 3083
* HaoIDE 3.0.9

**Comment by Shababsoft** [comment]
When I use the disable_visualforce_completion = true, there is no delay on Visualforce page but it stops the auto-complete functionality.

**Comment by xjsender** [comment]
@Shababsoft , this settings is used to disable all completion in visualforce page indeed, can you record a gif demo to show what happened in your computer?

**Comment by Shababsoft** [comment]
![haoide](https://cloud.githubusercontent.com/assets/4686730/8657185/10940b38-2994-11e5-8a79-f835d24922e5.gif)

**Comment by Shababsoft** [comment]
@xjsender You can see the delay in the above gif image.

**Comment by xjsender** [comment]
@Shababsoft , I saw the delay, how about the hardware of your computer? Which version of this plugin can work find in your computer? Since which version, delay happened in your computer?

**Comment by Shababsoft** [comment]
I have Dell XPS 13 (Intel i7, 8GB RAM and 512 SSD). Currently I am using the latest version of HaoIDE (3.1.0). I am facing this issue since version 3.0.9

**Comment by xjsender** [comment]
@Shababsoft , I just compared 3.0.9 with 3.0.8, I didn't find any updated code related to visualforce completion, so I will add four settings in  ``release v3.1.1`` as below to disable part completion feature of visualforce page, you can try to test which part cause your problem.

* ``disable_component_attribute_completion``
* ``disable_component_attribute_value_completion``
* ``disable_custom_component_completion``
* ``disable_apex_completion_in_visualforce``

**Comment by xjsender** [comment]
@Shababsoft , [``v3.1.1``](https://github.com/xjsender/haoide/releases/tag/v3.1.1) is released now.

**Comment by Shababsoft** [comment]
The following setting did not work for me.

disable_component_attribute_completion = true
disable_component_attribute_value_completion = true
disable_custom_component_completion = true
disable_apex_completion_in_visualforce = true

Please can you try in your system

**Comment by xjsender** [comment]
@Shababsoft , I just tried in mac and windows, it worked. How did you try?

**Comment by Shababsoft** [comment]
I add the following lines in the HaoIDE User Setting

**Comment by Shababsoft** [comment]
I had SublimeCodeIntel installed in sublime, after disabling it code auto-complete doesn't work on visualforce page even disable components are false. Is HoaIDE depends on it to autocomplete?

**Comment by xjsender** [comment]
@Shababsoft , HaoIDE is not depend on other plugin, especially these four settings, after you setting the four flag to true, you will not get attribute completion and attribute value completion but you can still get tag name completion, did your sublime just like this after disabled these four settings?

**Comment by Shababsoft** [comment]
I am still facing issue after change all the disable settings to true. Even I disable the other packages.. I am still facing delay on the visualforce page, but when I disable the HoaIDE, everything works fine. It is very strange.

**Comment by xjsender** [comment]
Can you try to install haoide to a brand new installed sublime, I am afraid it is due to lots of cache file in your exist sublime.

**Comment by Shababsoft** [comment]
Fresh installation resolved the issue.
