### ISSUE TITLE
No Cache, Please New Project Firstly error

### ISSUE THREAD

**Issue by Ibfreeman** [xjsender/haoide#53]
We are having a issue when one developer creates an object that is deployed to server, but mine will not pull it down correctly. For example: I need to create a trigger / class for a object called ShipmentLineItem__c. I tried to create a new project to refresh my current project, and I can see that it pulled the file down. But when I go to create a new trigger I get the error "No Cache, Please New Project Firstly." Not sure if it is a process with how we are doing it, or if it is a bug on your end. I tried to refresh the cache.
![sublime error](https://cloud.githubusercontent.com/assets/7295570/8679989/2c6076ec-2a13-11e5-9f89-fe52c8622397.png)

**Comment by xjsender** [comment]
@Ibfreeman , this alert message is not very clear, I will change it to a clear description, sorry about that.
 
Actually, you should execute ``Cache > Reload Sobject Cache`` in the main menu

**Comment by Ibfreeman** [comment]
I have tried that, and nothing happens. I have also tried Project > Update Project. Every time I try to create a new trigger, all I get is "No Cache, Please New Project Firstly." I have even tried New > New Project to refresh my current project and no luck.

**Comment by xjsender** [comment]
@Ibfreeman , when you reload sobject cache, there will have a progress information in the status bar, after the progress information is disappeared, you can go to next step, did you do it like this?

**Comment by Ibfreeman** [comment]
Looks like you patch worked! Yes that was how I was doing it. It was never
loading the progress bar.

**Comment by xjsender** [comment]
If any question, please reopen this issue, thanks for your support.
