### ISSUE TITLE
Fast deploy current class to current instance

### ISSUE THREAD

**Issue by maksimln** [xjsender/haoide#54]
Can you do bind hotkey (like alt+cmd+d) for fast deploy current class to current instance?

I mean when I try to deploy the current class I should select an instance and it is not comfortable.

**Comment by xjsender** [comment]
@maksimln , I just released a pre-release version [``v3.1.1``](https://github.com/xjsender/haoide/releases/tag/v3.1.1), you can download the ``sublime-package`` via this [url](https://github.com/xjsender/haoide/releases/download/v3.1.1/haoide.sublime-package)

**Comment by xjsender** [comment]
[``v3.1.1``](https://github.com/xjsender/haoide/releases/tag/v3.1.1) is released now.

**Comment by maksimln** [comment]
Sorry for later response about this issue

quick deploy not check current project but save to server check this

I mean:
Set active project A 
Open project B and open a file from B project 
Try to quick deploy this file 
    - deploy will start to incorrect server but should be as save to server (Error: This project is not active project) 

It is important for me because of I develop features for one project on other orgs and I can deploy not complete class to main org with managed package

Thanks!

**Comment by xjsender** [comment]
understood
