### ISSUE TITLE
RunTestCommand not functioning properly

### ISSUE THREAD

**Issue by reyesml** [xjsender/haoide#55]
After upgrading from build v3.1.0 to build v3.1.1 I can no longer run apex tests by using the keyboard shortcut ctrl+alt+T, or by right-clicking my open test class and selecting the "Run Test Class" command.

I suspect the issue is on line 1184 of main.py.  You removed "self" in your most recent build:
(Current) v3.1.1
`attributes = util.get_file_attributes(view.file_name())`

(Previous) v3.1.0
`name, extension = util.get_file_attr(self.view.file_name())`

I'm at the office right now, but I will verify this after I get home in the evening and create a pull request if I'm successful.  If adding "self" doesn't fix it, then i'll dig deeper into the `get_file_attributes()` method.

If anyone else is experiencing the same issue, my current workaround is to type alt+T, then search for the test class by name.  Or you can use the main HaoIDE menu:  HaoIDE > Debug > Run Test.

I'm using Windows 8, SublimeText Build 3083

**Comment by xjsender** [comment]
@reyesml , yes, it's a bug, in the latest release, I made significant change for supporting deploy or retrieve of inFolder Metdata Objects, however, I didn't perform comprehensive test on it.

Thanks for yor reporting on this issue, I will release a hot-fix release to fix this issue.
