### ISSUE TITLE
crtl+alt+c : code coverage disable in V3.1.2

### ISSUE THREAD

**Issue by ZeTomate** [xjsender/haoide#56]
Since the last release (v3.1.2), "Crtl+Alt+C" doesn't work, even after running the test and seems to be disable.
add : { "keys": ["ctrl+alt+c"], "command": "view_code_coverage" } the the User -keybinding - doesn't change a thing.
Would it be possible the enable the command ?
Thx

**Comment by pewho** [comment]
I've the same issue, it appears with the last revision, i think.
Right click on a class or a trigger + "HaoIDE > View Code Coverage" seems to be disabled, too.

**Comment by xjsender** [comment]
sorry for the trouble., I will do a comprehensive check on all feature tonight.
