### ISSUE TITLE
Unable to save components with the Reports.ReportResults Type When Referencing a Property

### ISSUE THREAD

**Issue by SLS-ThomasMcFarlane** [xjsender/haoide#58]
I am unable to save components with the following lines:
```apex
<apex:component >
    <apex:attribute name="ReportTitle" description="Title of report"  type="String" required="true"/>
    <apex:attribute name="ReportResults" description="Reports.ReportResults"  type="Reports.ReportResults" required="true"/>
    {!ReportResults.Test}
</apex:component>
```

However I am able to save using the following code:
```apex
<apex:component >
    <apex:attribute name="ReportTitle" description="Title of report"  type="String" required="true"/>
    <apex:attribute name="ReportResults" description="Reports.ReportResults"  type="Reports.ReportResults" required="true"/>
    {!ReportResults['Test']}
</apex:component>
```

When referencing the parameter Test on ReportResults the HaoIDE plugin will "save" without any error validation (anything can be incorrect and it will not provide an error) however this does not commit to Salesforce.
Replacing the property with the index allows this to save as expected and commit to the server with validation checking.

**Comment by xjsender** [comment]
@SLS-ThomasMcFarlane , it's a tooling api flaw, tooling API detect an error but can't detect the error type and give a unknow exception, this plugin didn't catch this type of exception, I will fix this issue in the next release, thanks for your report.

**Comment by SLS-ThomasMcFarlane** [comment]
@xjsender awesome; just to clarify - there seems to be two issues here.
Initially it is the fact that you cannot save the file to Salesforce if you are referencing a property on the Reports namespace - even if this property is fully valid.
The second is, as you pointed out, that errors are not being handled correctly for this.

**Comment by xjsender** [comment]
@SLS-ThomasMcFarlane ，

The first one as you point is due to tooling api issue, as you know, tooling api  is not stable especially during special situation just like the one you met, If you encounter this problem, you should switch to ``Deploy to This Server`` command.

The second one as you point is plugin issue, which will be fixed in the next release.

Hao

**Comment by xjsender** [comment]
@SLS-ThomasMcFarlane , v3.1.4 is released.
