### ISSUE TITLE
No debug logs when running unit test from Haoide

### ISSUE THREAD

**Issue by fricco** [xjsender/haoide#6]
Hello, when running unit test from Haoide, I'm not getting a LogId result, and even if I have my user added to the Monitored Users, it seems that is even deleted from there after running the test.
Just in case, in my user settings, I have:
"trace_flag":
	{
		"ApexCode": "Debug",
		"ApexProfiling": "None",
		"Callout": "None",
		"Database": "None",
		"System": "None",
		"Validation": "None",
		"Visualforce": "None",
		"Workflow": "None"
	}

**Comment by xjsender** [comment]
@fricco ， I can't replicate your issue, can you paste your test result to here.

**Comment by fricco** [comment]
Here is the result I'm getting:
Fricco_DummyTest Test Result
----------------------------------------------------------------------------------------------------
                  MethodName:     testUnshareRecords            
               TestTimestamp:     2015-02-04T14:33:46.000+0000  
                   ApexClass:     Fricco_DummyTest              
                   Pass/Fail:     Pass                          
               Error Message:                                   
                 Stack Trace:                                   
-------------------------------------------------------------------------------
You can choose the LogId and view log detail in Sublime or Salesforce by context menu
-------------------------------------------------------------------------------
LogId: 
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
[List of Classes with their coverages]

**Comment by xjsender** [comment]
@fricco , what's the version of your plugin?

**Comment by fricco** [comment]
v2.7.8

**Comment by xjsender** [comment]
@fricco , can you execute the rest tooling query as below screenshot and paste the result to here.

You need to replace the ```TracedEntityId``` with yourself
![image](https://cloud.githubusercontent.com/assets/1450977/6043336/8bce457a-acc6-11e4-92b7-c4e9af60edcb.png)

**Comment by fricco** [comment]
{
    "totalSize": 1, 
    "size": 1, 
    "records": [
        {
            "attributes": {
                "url": "/services/data/v32.0/tooling/sobjects/TraceFlag/7tfq00000004GDTAA2", 
                "type": "TraceFlag"
            }, 
            "Id": "7tfq00000004GDTAA2"
        }
    ], 
    "done": true, 
    "entityTypeName": "TraceFlag", 
    "queryLocator": null
}

**Comment by xjsender** [comment]
@fricco , sorry, I can't replicate your problem.

**Comment by fricco** [comment]
Something that I saw and may be related, is that when saving, refreshing or running test from Haoide, my user is deleted from the Monitored Users

**Comment by ecastillo550** [comment]
I am having the exact issue, my user gets deleted from monitored users when I run a test.

**Comment by fricco** [comment]
ecastillo550, this happens when saving or refreshing from HaoIDE?

**Comment by xjsender** [comment]
@fricco , @ecastillo550 , I exactly delete the monitored user when you run test, track debug log or save file to server, due to xjsender/SublimeApex#24, you can have a look.

I will add a setting to control whether clear the history debug log in the next release.

**Comment by xjsender** [comment]
@fricco , please help to confirm, thanks.

**Comment by fricco** [comment]
@xjsender , I'm still having the same issue, at least when running a unit test, is still deleting my user in the Monitored User and no LogId is retrieved in the Test Result tab.

**Comment by xjsender** [comment]
@fricco , what's your plugin version, I released a new v2.8.1 version yesterday night, did try to running test after you upgrade this plugin? 

I have removed the delete logic in the new release, it should't happen again.

**Comment by fricco** [comment]
@xjsender , I upgraded yesterday to v2.8.1 and after that I tried it, and didn't work. Just in case today I test it again, and now it seems to be working, although I need to manually add my user into the monitored users in salesforce before running the test. The track self and track my user options are not working. If I don't add my user manually in the monitored users, the LogId is still blank in the test result tab.

**Comment by xjsender** [comment]
@fricco , I can't replicate your problem, it's very strange.

**Comment by fricco** [comment]
@xjsender did you tried to replicate this by first removing you user from the Monitored users in Salesforce and then running a unit test from HaoIDE?

**Comment by xjsender** [comment]
@fricco , I tried, but not replicate it.

**Comment by reyesml** [comment]
I'm having the same issue, and I think it might be caused by the ExpirationDate that's set in create_trace_flag function.  I'm in the pacific time zone, and the ExpirationDate sent to salesforce is 2 hours in the future, relative to pacific time.  Since pacific time is 7 hours behind GMT, the ExpirationDate being sent to salesforce is already expired.

I'm running Windows 8, SublimeText Build 3083, and Haoide Build v3.0.5

**Comment by xjsender** [comment]
@reyesml , can you submit a pull request for this issue?

**Comment by reyesml** [comment]
@xjsender , I submitted the pull request.  Let me know if you need anything else.

**Comment by xjsender** [comment]
@reyesml , because I can't replicate this issue, so I need you to ensure this pull request fixed this issue, thanks, did you test it?

**Comment by reyesml** [comment]
@xjsender , yes, I tested it.  Before my change, the logId on the testResults screen was blank.  After my change, the logId was present, and I was able to highlight the logId and select "HaoIDE > View Debug Log Detail"

![fixeddebuglogid](https://cloud.githubusercontent.com/assets/4985056/8297523/33c6b01a-1913-11e5-9fcd-6aa10b111c00.jpg)
![fixeddebuglog02](https://cloud.githubusercontent.com/assets/4985056/8297524/33c6eef4-1913-11e5-8d9e-0e71a2f8acfc.jpg)

**Comment by xjsender** [comment]
@reyesml , thanks for your help, I will merge it.

**Comment by xjsender** [comment]
@fricco , @ecastillo550 , could you help us check the pull request by @reyesml , thanks. The pull request is included in release v3.0.6.
