### ISSUE TITLE
"Run Sync Test" opens blank window

### ISSUE THREAD

**Issue by reyesml** [xjsender/haoide#60]
I'm using Haoide v3.1.5 and sublime Build 3083 on a Windows 8 machine.

The "Run Sync Test" command only opens a blank window.  The "Run Test Class" command still works, but when i try to view code coverage for a class I get this error message in the console:

"No code coverage cache, please execute `Run Sync Test` on related test class before view code coverage"

**Comment by xjsender** [comment]
@reyesml , did you get any error message in the console? If not, can you try to set the ``debug_mode`` setting to ``true`` before run test.

**Comment by reyesml** [comment]
There are no error messages in the console.  I changed `debug_mode` to `true` and no information was displayed in the console, and no other debug windows were opened.

I'm using Fiddler to examine my network packets, and I can confirm that Haoide is getting a valid response from `/services/data/v34.0/tooling/runTestsSynchronous/`.

**Comment by xjsender** [comment]
it should have a raw response displayed in a view.

**Comment by xjsender** [comment]
@reyesml , did your class have namespace? there has problem when run sync test class for it. I will release a new version to quick fix this issue.

**Comment by reyesml** [comment]
@xjsender , my class doesn't have a namespace.

**Comment by xjsender** [comment]
@reyesml , if you open the ``debug_mode``, did you get a new view with any json response?

**Comment by reyesml** [comment]
@xjsender , i set debug_mode to true, and i did not get a new view with json.  When I was testing earlier, i was using my Windows 8 machine at my office.  I just tested the `run sync test` command in OSX and it worked perfectly.  The issue appears to be isolated to Windows.  I'll see if I can give you more information after I return to the office tomorrow.

**Comment by xjsender** [comment]
@reyesml , I just tried to replicate this issue in my mac computer, now, I will try it in my windows computer, thanks for your response.

**Comment by xjsender** [comment]
@reyesml , I tried in my windows7 compurter but I didn't replicate this issue, can you please debug it in your computer and request a pull request for this issue? thanks.

**Comment by reyesml** [comment]
@xjsender , I'll take a look this weekend.

**Comment by reyesml** [comment]
@xjsender, this issue was resolved in the most recent release of haoide (v3.1.6)
