### ISSUE TITLE
"Diff With Server" fails on cross-org diff

### ISSUE THREAD

**Issue by reyesml** [xjsender/haoide#61]
I'm using haoide v3.1.5, Sublimetext build 3083 on Windows 8.

I have a Production salesforce org and a Sandbox for this org.  In haoide v3.1.3, I was able to diff the sandbox version of a file to the production version using the "Diff With Server" feature.  Since I upgraded to v3.1.5, I get the following error message if I try to diff my sandbox file against the production server:

`[2015.07.27 17:09:39] [ERROR] This component is not exist in chosen project`

**Comment by xjsender** [comment]
This is not a issue, please try to update your pro project before diff, I have mentioned this change in the release note.

**Comment by reyesml** [comment]
@xjsender , i updated both my sandbox and production projects, and I still receive the same error.

**Comment by reyesml** [comment]
@xjsender , thanks!  This works perfectly now.
