### ISSUE TITLE
Refresh folder or update project is not working

### ISSUE THREAD

**Issue by sujaka** [xjsender/haoide#70]
When I want to pull changes in the project I click on refresh this folder or update project but It does not reflects new changes in the files.

I did above operation to pull new visulaforce changes.

**Comment by xjsender** [comment]
@sujaka , as you know, every project has a time suffix, is your project created at today? If not, your refreshed file will be kept at a new project with the latest time suffix.

**Comment by sujaka** [comment]
@xjsender  thanks for your prompt response. This project is really cool but I just want to understand why I cant see refresh page when I click on retrieve from server.

is it not confusing that I am clicking on refresh but cant see the changes.

**Comment by xjsender** [comment]
Did my above response answer your question?

**Comment by sujaka** [comment]
I created my project today and one of my colleague created some object in salesforce and I want to pull them but I cant see any changes when I update the project.

**Comment by sujaka** [comment]
This is working now and I understood the functionality of this app.
