### ISSUE TITLE
[Suggestion] Enable auto-deploy to server option when saving a file

### ISSUE THREAD

**Issue by lance-shi** [xjsender/haoide#72]
It's time-consuming to have to find the file in sidebar every time I want to save a file to server. Should enable saving file to server option like Eclipse force.com IDE and MavensMate does.

**Comment by xjsender** [comment]
@lance-shi , why do you need to save file to server in the sidebar? This plugin has so many commands you need the context menu.

![image](https://cloud.githubusercontent.com/assets/1450977/9539756/e3ccef34-4d88-11e5-9b33-0bbd3d61d5bc.png)

**Comment by lance-shi** [comment]
Yep, thanks for that. I just switched from MavensMate to HaoIDE and still investigating. I do agree there are multiple ways save to server now, which should be good. Because I just realized HaoIDE generally uses multiple file deployment to save time. 

But just one more question, there is only one option to deploy all open files to server, but generally we are opening a lot of tabs during development, and probably not planning to deploy all of them. Is there any planning about to deploy only a selection of them?

**Comment by xjsender** [comment]
@lance-shi , your idea about ``deploying part of open files to server`` is feasible, however, can you please log a new issue to record this idea?

**Comment by lance-shi** [comment]
Sure. I will close this issue now. Thank you.

**Comment by xjsender** [comment]
@lance-shi , the new issue?

**Comment by lance-shi** [comment]
I am trying to add your qq account. Having some suggested features wanna discuss with you

**Comment by xjsender** [comment]
30156309
