### ISSUE TITLE
[Question] Is there a reason generating a new folder for each project everyday instead of using just one folder

### ISSUE THREAD

**Issue by lance-shi** [xjsender/haoide#74]
I am seeing HaoIDE is generating a new folder based on the current date for each project everyday. And Once I refresh from the server, it will create a new file in the new folder. But the old one is not removed. Is there any reason why it is working this way? Or is it a bug?

**Comment by DrByrnes** [comment]
You can disable that option by adding the follow setting in HaoIDE --> Settings --> Setting - User:

"keep_project_name_time_suffix": false

**Comment by lance-shi** [comment]
@DrByrnes Thank you for the answer. But is there a reason why this is not default?

**Comment by DrByrnes** [comment]
I have no idea.  I'm not part of the dev team (and haven't contributed to this project yet either).  I'm just an avid user!  ;-)

**Comment by xjsender** [comment]
@lance-shi , because many of us don't have source control system, so I set this settings to default true.

Thanks for your help, @DrByrnes.

**Comment by lance-shi** [comment]
Thank you for this. I am using the below settings for my project but still doesn't work for me: 
"Exchange-Dev-HaoIde":
		{
			"allowed_packages":
			[
			],
			"default": true,
			"keep_project_name_time_suffix": false,
//...

Before setting and saving this into my user setting, I already had the folder C:\HaoIDEProjects\Workspace\Exchange-Dev-HaoIde-20150828 created. When I refresh class and page folder from exchange, It still generates a new folder. How can I handle that?

**Comment by xjsender** [comment]
@lance-shi , you put the ``keep_project_name_time_suffix`` to wrong place, it should be in the same level of ``projects`` setings.

**Comment by xjsender** [comment]
@lance-shi , all your custom settings should follow the rule of default settings.

**Comment by lance-shi** [comment]
I have updated my user settings into this: 
{
	"keep_project_name_time_suffix" : true,
	"projects":
	{
		"Exchange-Dev-HaoIde":
//...

And deleted the existing new date folder. But once I switched to the project, a new folder with date suffix is still created.

**Comment by xjsender** [comment]
@lance-shi ,  You need to set ``keep_project_name_time_suffix`` to ``false``.

**Comment by lance-shi** [comment]
Thank you for that. My bad for being that careless... It's working now. Thank you for that.
