### ISSUE TITLE
Is there something wrong with deploying objects?

### ISSUE THREAD

**Issue by Xtremefaith** [xjsender/haoide#78]
I have a custom object with custom fields, lets call it `Custom__c.object`. So I had a duplicate field and I removed it through the admin site in my production and then I pulled the `Custom__c.object` metadata file down and as expected the field is gone. So then I deployed that same object file to my sandbox org and I got a success message but when I refresh the object the fields are still present.

I attempted both "Deploy to Server" and "Deploy to this Server" and both do the same thing, success message but no change. Any ideas what the problem could be?

**Comment by xjsender** [comment]
@Xtremefaith , maybe it is the problem of metadata, did you try to do it by ANT or eclipse?

**Comment by xjsender** [comment]
@Xtremefaith , Metdata API can't remove field by this method, if you want to remove field.
