### ISSUE TITLE
Enable refreshing the whole project

### ISSUE THREAD

**Issue by lance-shi** [xjsender/haoide#79]
As working in a multi-developer team, what I usually need is simply to refresh the whole project, not just the class, trigger or pages folder. I wish HaoIDE could provide the option

**Comment by xjsender** [comment]
@lance-shi , already have, you can do it by ``Update > Update Project`` in the main menu.

**Comment by xjsender** [comment]
@lance-shi , how is going on this issue, did you check it?

**Comment by lance-shi** [comment]
Yes, it is working fine. Thanks for the comment. Closing the issue now.
