### ISSUE TITLE
Request for new feature:  deploy to a different org

### ISSUE THREAD

**Issue by lucheng1** [xjsender/haoide#8]
Would you add the support for deploying the selected file to an Org that's different from what's configured for the current project.    Thanks!   Btw, Awesome project!

**Comment by xjsender** [comment]
@lucheng1 , already have, see [Deploy Files to Server](https://raw.githubusercontent.com/xjsender/SublimeApexScreenshot/master/DeployFilesToServer.gif)

**Comment by xjsender** [comment]
@lucheng1 , or, you can open the files from different orgs and use ```HaoIDE > Migration > Deploy Open Files to Server``` in the main menu to deploy them to different orgs.

**Comment by lucheng1** [comment]
@xjsender, my bad! From your response I just realized that I need to add the other orgs as separate projects in the user setting and then I am able to deploy to those other projects!   Thanks you!
