### ISSUE TITLE
While coding lightning app/component, controller/helper js files got reset to the default contents

### ISSUE THREAD

**Issue by royluo6** [xjsender/haoide#80]
Here are the steps to reproduce the issue:
1. Use Developer Console to create a Lightning Component, add some dummy codes to controller/helper js.
2. Use HaoIDE to retrieve all Lightning items.
3. Open the component .cmp file at aura folder with HaoIDE, make some change, then save the component 
4. Go back to Developer Console and reload the component.
5. The js codes you put in at step 1 all gone.

**Comment by xjsender** [comment]
@royluo6 , I just did it as your steps, however, I can't replicate this issue.

Usually, after made some change on the component in the HaoIDE, you should press ``Alt+Shift+S`` to sync your change to server, did you do that?

**Comment by royluo6** [comment]
Yes, I did use Alt+shift+s to save the component. Could it be some setting somewhere?

I would try again tomorrow. Maybe I should update js files then save to the server via haoIDE. Will update you what I see tomorrow.

Thanks,
Roy

On Nov 3, 2015, at 8:08 PM, Hao Liu <notifications@github.com<mailto:notifications@github.com>> wrote:


@royluo6<https://github.com/royluo6> , I just did it as your steps, however, I can't replicate this issue.

Usually, after made some change on the component in the HaoIDE, you should press Alt+Shift+S to sync your change to server, did you do that?

**Comment by xjsender** [comment]
@royluo6 , how is going on this issue?

**Comment by xjsender** [comment]
@royluo6 , you can try it with new version.

**Comment by royluo6** [comment]
Yes, it works now! Thanks a lot.
