### ISSUE TITLE
Session is expired, need login again never stop on switch project

### ISSUE THREAD

**Issue by maksimln** [xjsender/haoide#81]
SF password for account should be expired
1. Open Sublime 
2. Select HaoIDE->Switch Project menu item
--> Session is expired, need login again never stop on switch project (in status bar Describe Metadata... )

http://take.ms/gW8Af

Copyright © 2013-2015 By Hao Liu
Dev Channel, Build v3.2.0

**Comment by xjsender** [comment]
@maksimln , I also met this error and already fixed it.
