### ISSUE TITLE
Include the option to use Metadata API instead of Tooling API

### ISSUE THREAD

**Issue by lance-shi** [xjsender/haoide#82]
Not sure whether has already been implemented or not, but I didn't find the related option in the settings file. The IDE should provide the ability to use Metadata API instead of Tooling API. 

The requirement for this is because tooling API is having an issue (not sure whether bug or not) with calling global class from other package. Will throw type not visible error. This is because Tooling API cannot handle the version of metadata file. Metadata API will not have such an issue

**Comment by xjsender** [comment]
@lance-shi , the below four commands in the picture are using ``Tooling API``, others are using ``Metadata API``, so option is needless.

![image](https://cloud.githubusercontent.com/assets/1450977/11709285/45c84214-9f51-11e5-80ae-35add0bca176.png)
