### ISSUE TITLE
Error creating a debug log

### ISSUE THREAD

**Issue by weivreca** [xjsender/haoide#83]
Hi,

When I go to create a debug log (any of the debug options) I get this error. Thanks 

url: 	https://emeraldgrain--UAT.cs31.my.salesforce.com/services/data/v35.0/tooling/sobjects/TraceFlag	
 Time Stamp: 	2015-12-14 09:44:08           	
 fields: 	LogType                       	
 message: 	LogType is required.: LogType 	
 errorCode: 	FIELD_INTEGRITY_EXCEPTION

**Comment by xjsender** [comment]
@weivreca , workaround is to low down your ``api_version``, I will fix it in the next release.

**Comment by weivreca** [comment]
Thanks for the quick feedback!

**Comment by xjsender** [comment]
@weivreca , this is a issue, I will close the issue after I really fixed it.
