### ISSUE TITLE
'Retrieve from Server' not working

### ISSUE THREAD

**Issue by DrByrnes** [xjsender/haoide#85]
When right-clicking a class (that exists in multiple orgs) and selecting 'Retrieve from Server' I'm prompted 'Am I sure?' which I click 'Confirm?'.  I then select the org to retrieve it from, confirm again (side-note:  please remove the first dialog box) and the API goes to work allegedly refreshing the file, but I'm not seeing anything change locally.

I manually logged into the other org to confirm that the code was indeed different.

This is on the latest version, 3.2.5.

**Comment by xjsender** [comment]
@DrByrnes , yes, I can replicate the issue, thanks for your response.

BTW, the duplicate confirmation problem will also be fixed in the next release.
