### ISSUE TITLE
Debug Tracking not working for API 35

### ISSUE THREAD

**Issue by weivreca** [xjsender/haoide#86]
Hi,

I'm getting the following error when trying to set a debug log with API 35 (API 34 works fine)

No such column 'TracedEntityId' on sobject of type DebugLevel

Thanks

**Comment by xjsender** [comment]
@weivreca , what's the plugin version you are using?

**Comment by xjsender** [comment]
@weivreca , its a bug, thanks for your response.

**Comment by xjsender** [comment]
Also fixed issue #84
