### ISSUE TITLE
Ability to create static resource

### ISSUE THREAD

**Issue by ashishcloud** [xjsender/haoide#87]
Hi,
There is no option to create static resource. 
Right now we have to create static resource from developer console and then have to update project.
This is really very painful.

Is there any way by which we can create static resource from HAOIDE.
Thanks

**Comment by xjsender** [comment]
@sujaka , I don't know how to detect the ``MIME TYPE`` of your uploaded file and the ``MIME TYPE`` field is required.

Do your have any opinion on it?

**Comment by xjsender** [comment]
Duplicate with issue #9 , enhancement request for adding feature for ``Static Resource CRUD By Tooling API``
