### ISSUE TITLE
There is no available test class

### ISSUE THREAD

**Issue by Shababsoft** [xjsender/haoide#88]
Hi @xjsender 

I am getting the '**There is no available test class**' error message, everytime I click the Run Tests option under debug. I cannot see the **Run Sync Test** option on a test class but can run the test class using **Run Test Class**

Environment: Developer ORG

**Comment by xjsender** [comment]
@Shababsoft , this issue is fixed in the release 3.2.8.

**Comment by Shababsoft** [comment]
Thanks. Do you know when are we going to get this release on the sublime text?

**Comment by xjsender** [comment]
@Shababsoft , I don't know why package control can't publish the release automatically, I will try to update the release again for that.

**Comment by xjsender** [comment]
@Shababsoft , there are some problem within package control, see [this](https://github.com/wbond/package_control_channel/issues/5283) for detail

**Comment by Shababsoft** [comment]
@xjsender  I am getting this error again for the Developer org

**Comment by xjsender** [comment]
@Shababsoft , I saw this error before you log the issue, which caused by ``refresh_package`` command, I already fixed it.
