### ISSUE TITLE
Match timestamp on save to avoid ovewrite existing component

### ISSUE THREAD

**Issue by Shababsoft** [xjsender/haoide#89]
Hi @xjsender ,

Please can you add a new feature that diff the local file modified date and server modified date to avoid the overwriting issue. There is a same functionality in Eclipse that shows an error if file is not sync with server.

For example, if I modify an apex class in Salesforce and then if I save the old version of the class from HoaIDE that overwrites the latest version of the class.

**Comment by xjsender** [comment]
@Shababsoft , I noticed there are two Date fields on the object, ``SystemModstamp`` and ``LastModifiedDate``, after check the [difference between the two fields](http://salesforce.stackexchange.com/questions/7327/what-is-the-difference-between-lastmodifieddate-and-systemmodstamp), I think,  if use ``haoide`` to execute save operation, we can check the value of the two date fields, only if the two values are equals, ``save operation`` can continue, can it solve your problem?

**Comment by xjsender** [comment]
@Shababsoft , I just finished the feature as you wanted, however, I need to test it before release it.

If you want to try this feature before released, I can upload the trial package to here.

**Comment by Shababsoft** [comment]
@xjsender, Yes please, If you can upload the package I will be able to test this feature.

**Comment by xjsender** [comment]
@Shababsoft , [Pre-release 3.2.9](https://github.com/xjsender/SublimeApexScreenshot/raw/master/haoide.sublime-package)

**Comment by Shababsoft** [comment]
Thanks @xjsender , now I am getting the "Modified by _My Name_" message every time I save a file. I think we might have to keep the Last Modified Date of a file locally after successful save and match against the server file on next save.

**Comment by xjsender** [comment]
@Shababsoft , you are right, I also got the same problem.

As the original design, I keep the ``LastModifiedDate`` from the last save operation reqsponse to local cache, if we save the file again, I will compare the cache date with LastModifiedDate in server, if they are not same, ``conflict warning`` will alert.

Actually, there have 1s to 4s gap between the local ``LastModifiedDate`` and server ``LastModifiedDate``, I don't know why it happened.

I will continue investgating on it, thanks for your report.

**Comment by xjsender** [comment]
@Shababsoft , I just uploaded the revised version to [Pre-release 3.2.9](https://github.com/xjsender/SublimeApexScreenshot/raw/master/haoide.sublime-package), please try it again.

Originally, I just keep the ``LastModifiedDate`` from save response to local cache, in order to avoid the 1-4 seconds difference between the date values, I discard the ``LastModifiedDate`` from the response result and change to query the ``LastModifiedDate`` from server if save operation is succeed. When we execute the save operation in the next time, we will use compare the ``LastModifiedDate`` in the local cache with server.

**Comment by Shababsoft** [comment]
@xjsender Thanks. I am still getting the Last Modified popup window every time I save a class.

**Comment by xjsender** [comment]
@Shababsoft , did you restart your sublime after put the new version to the ``Installed Package`` path of sublime? I just tried, everything is ok.

**Comment by xjsender** [comment]
@Shababsoft , actually, you are right, there is a flaw in it, I will release this version tonight, thanks for your help on this feature.

**Comment by xjsender** [comment]
@Shababsoft , I just found a bug, I will revert the new release and release it again after fix it.

**Comment by xjsender** [comment]
@Shababsoft , the fixed version is already released, if it is ok, please help to close this issue, thanks.

**Comment by Shababsoft** [comment]
@xjsender Thanks this feature is working as expected. But now after run `update project` action I am able to overwrite a class that was modified by other user, without any confirm message box. Before I was use to get confirm message if class or page was modified by someone else.

**Comment by xjsender** [comment]
@Shababsoft , after you update the project, the class is the latest version, I think it should override the server version without any warning even if it is last modified by someone else.

**Comment by xjsender** [comment]
@Shababsoft , if you continue to think the ``lastModifiedBy check`` is needed, I can add it in the next release.

**Comment by Shababsoft** [comment]
@xjsender After updating to the v3.30, I am getting the `Modified by _Name_ at _DATE_TIME_, continue?` popup message, every time I save an apex component.

Yes, if you can add the lastmodifiedBy check that will be helpful. Thanks for your hard-work.

**Comment by xjsender** [comment]
@Shababsoft , can you paste the attribute the apex component to here by ``View File Attribute``

**Comment by Shababsoft** [comment]
{
    "fullName": "BigDonor", 
    "lastModifiedDate": "2016-03-09T22:17:06.000Z", 
    "is_test": false, 
    "fileName": "unpackaged/classes/BigDonor.cls", 
    "extension": ".cls", 
    "type": "ApexClass", 
    "url": "/services/data/v35.0/sobjects/ApexClass/01pb00000027CydAAE", 
    "body": "Body", 
    "name": "BigDonor", 
    "id": "01pb00000027CydAAE", 
    "namespacePrefix": ""
}

**Comment by xjsender** [comment]
Execute REST GET for this url ``/services/data/v35.0/sobjects/ApexClass/01pb00000027CydAAE`` and paste the ``LastModifiedDate`` in the response to here.

Every thing about the conflict check is ok for me, I am curious what happened in your computer.

**Comment by xjsender** [comment]
@Shababsoft , please, I need this.

**Comment by Shababsoft** [comment]
"LastModifiedDate" : "2016-03-11T09:37:24.000+0000", 
"LastModifiedById" : "005b0000000FbzUAAS",

**Comment by xjsender** [comment]
Obviously, the local cache is not refreshed after save operation, did you restart your plugin after new version is installed.

**Comment by Shababsoft** [comment]
@xjsender  I restarted couple of times. Should I uninstall and then install again?

**Comment by xjsender** [comment]
@Shababsoft , I will add the debug part in the next patch release.

I will add the ``lastModifiedBy`` check in the next release.
