### ISSUE TITLE
Can't activate HaoIDE

### ISSUE THREAD

**Issue by ZeTomate** [xjsender/haoide#90]
Since this morning I can't use HaoIDE. I can see the tab, but everythings is un-selectable.
I'm using Python 3.5.X, I have "request" and "urllib3" installed and i already tried to uninstall& reinstall HaoIDE.... 
Thanks for everithing
I'm available for additional informations
[logHAOIDE.txt](https://github.com/xjsender/haoide/files/162876/logHAOIDE.txt)

**Comment by xjsender** [comment]
@ZeTomate , you don't need to install standlone python, just if you installed the ``Sublime Text 3``?

Can you post the screenshot of your sublime?

**Comment by ZeTomate** [comment]
well, I was using HaoIDE and SublimeText3 until last week. that's why i'm surprised.

![capture d ecran de 2016-03-08 15-33-11](https://cloud.githubusercontent.com/assets/9694084/13604619/e4444a72-e543-11e5-9036-253c70939e36.png)

**Comment by xjsender** [comment]
@ZeTomate , did you change the python version not using the buildin python?

**Comment by xjsender** [comment]
@ZeTomate , the ``requests`` is the buid-in lib in haoide, you don't need to install it by yourself after you installed haoide

**Comment by xjsender** [comment]
@ZeTomate , how is going on this issue?

**Comment by ZeTomate** [comment]
Hello, sorry for the late response.
The bug seems to be corrected. I've got an other problem now, but the HaoIDE is enable. 
Thx you very much
