### ISSUE TITLE
package.xml file reset on project update

### ISSUE THREAD

**Issue by Shababsoft** [xjsender/haoide#91]
@xjsender  I have noticed that package.xml file gets reset if we perform the new / update project action. Please can you provide setting that allow to use the package.xml file instead of resetting the package.xml file to the components we specified in the HaoIDE project setting.

**Comment by xjsender** [comment]
@Shababsoft , you mean keep the ``package.xml`` unchange if you update project after ``toggle subscribed settings``? why do you need this?

**Comment by Shababsoft** [comment]
Yes, keep the `package.xml` unchanged on project update and pull all the components mentioned in the `package.xml` (i.e. like retrieve package.xml from server command).

I am not using the `toggle subscribed settings` to subscribe the meta-data as I think we cannot select specific objects using it.

We are using the Git repo and package.xml in the git branch gets changed with time to time as other people are working in the same branch. When I update the project it reset the package.xml and only retrieve components in `subscribed_metadata_objects`

**Comment by xjsender** [comment]
@Shababsoft , I see, I will add a setting to control it, which will be very ease because there already had a [parameter](https://github.com/xjsender/haoide/blob/master/util.py#L1244) for this, I will release a trial version for your use.

**Comment by Shababsoft** [comment]
Thanks @xjsender

**Comment by xjsender** [comment]
@Shababsoft , it's too late today, I will start it tomorrow, thanks for your supporting to this plugin.

**Comment by xjsender** [comment]
@Shababsoft , I add a new setting ``ignore_project_package_xml`` to control that, its default value is ``false``

**Comment by Shababsoft** [comment]
@xjsender . Package.xml remains unchanged after `ignore_project_package_xml: true` but still it only pulls meta-data components specified in `subscribed_metadata_objects`, not from package.xml. 

Is it possible when `ignore_project_package_xml: true` is specified in settings  we can pull meta-data based on the package.xml? 

Can we also move this setting to the project level? I mean under each project in the `projects` setting

**Comment by xjsender** [comment]
@Shababsoft , this is a very specified-purpose requirement, I need time to consider its necessary.

**Comment by Shababsoft** [comment]
@xjsender Can you provide an option like Eclipse / MavesMate app that looks for the package.xml in the path and retrieve the package.xml.

Example:
![sublimetext - haoide](https://cloud.githubusercontent.com/assets/4686730/13699231/fc65a0ea-e770-11e5-9576-fa6b8b979df2.jpeg)

**Comment by xjsender** [comment]
@Shababsoft , I will, meanwhile, I will remove the settings and related code added in this issue.
