### ISSUE TITLE
Reload SymbolTable Cache command is not working

### ISSUE THREAD

**Issue by Shababsoft** [xjsender/haoide#93]
`Reload SymbolTable Cache` command is not working since 3.2.8 release.

**Comment by xjsender** [comment]
@Shababsoft , what's the problem when you execute this command?

**Comment by Shababsoft** [comment]
@xjsender  App keep showing the `Reloading Symbol Tables` in the bottom bar of sublime text. 

![2016-03-22 11_50_53-photos](https://cloud.githubusercontent.com/assets/4686730/13950695/682096ee-f024-11e5-8d0e-d854028ce232.png)
