### ISSUE TITLE
Ignore conflict issue

### ISSUE THREAD

**Issue by eugene-vabishchevich** [xjsender/haoide#95]
Hey!

Just got 3.3.0 version. And now after I'm saving controller or page I got message like:
"Modified by {!User_SFDC} at 2016-03-14 13:15:35, continue?" and cancel and ignore conflict buttons. It is always display my last saving date.

Can you help me with that? It's annoying.

**Comment by xjsender** [comment]
You can update to v3.3.2 to fix the problem

**Comment by eugene-vabishchevich** [comment]
Thanks!

**Comment by xjsender** [comment]
Duplicate with issue #89

**Comment by Shababsoft** [comment]
@xjsender I am facing this issue in the latest release.

**Comment by xjsender** [comment]
@Shababsoft , every time when you succeed to save the class to server, there will have a async thread to fetch the ``LastModifledDate`` of the class from server, and then keep it to local.

So if you start to save the class immediately after last save operation, the fetching thread is still in running, at the moment, the timestamp will not match, plugin will alert you.

As my thought, generally, it should have 30 seconds interval between two save operation, at least, it is ok for me.

If it is not ok for you, I think, we can consider to change the ``fetching thread`` to sync operation, however, it will spend more time to finish save operation.

So what do you think?

Thanks.

**Comment by Shababsoft** [comment]
@xjsender  Thanks for clarification, i think it is good to have settings to switch between Async and Sync for save, fetching and other actions.
