### ISSUE TITLE
Not able to save a new component after Refresh Package

### ISSUE THREAD

**Issue by Shababsoft** [xjsender/haoide#97]
@xjsender  I am not able to save a component after refreshing the project using the `Refresh Package` command. I am getting the following message: `This component is not in active project`. 

This is only happening for components created outside of the HoaIDE, The only way to save the components is to run the `Update Project` command first to refresh the project but this updates the `package.xml` file.

**Comment by xjsender** [comment]
@Shababsoft , yes, this is a problem. I will fix it in the next release.
