### ISSUE TITLE
export custom fields error

### ISSUE THREAD

**Issue by natotang** [xjsender/haoide#98]
When occurred when exporting custom field via Haoide, detail error message is attached below.
Looks like the summer 15 release restricts the user from querying more rows from custom field object if fullname field is in the query.

errorCode: 	MALFORMED_QUERY               	
                     message: 	When retrieving results with Metadata or FullName fields, the query qualificatio​ns must specify no more than one row for retrieval.

**Comment by xjsender** [comment]
@natotang , as you see, if we want to export all fields, we need to remove the FullName field from SOQL.

**Comment by natotang** [comment]
Cool man.
