### ISSUE TITLE
"Open Documentation" broken

### ISSUE THREAD

**Issue by superdave7380** [xjsender/haoide#99]
v3.3.6
**Open Documentation** & **Open Documentation By Type** options greyed out (unclickable).
Error messages on **Reload Salesforce Document**:
- _Failed to reload Metadata API Developer Guide, reason: [Errno 2] No such file or directory_
- Similar error messages for all documents.

Thanks!

**Comment by xjsender** [comment]
@superdave7380 , yes, its' a issue and already fixed, see the latest commit, I will release the new version today.

**Comment by superdave7380** [comment]
Perfect. Thanks very much. And keep up the great work!

**Comment by xjsender** [comment]
@superdave7380 , thanks.

**Comment by superdave7380** [comment]
Hey,

Docs options still grayed out on new release. And new error message on attempt to Reload:
_Failed to reload Metadata API Developer Guide, reason: No JSON object could be decoded_
(same message for all docs)

**Comment by xjsender** [comment]
@superdave7380 , I have already added the reference cache as a build-in module into the plugin, you don't need to reload the document after you reinstalled the plugin, however, I really hope you can tell me what happened, thanks.

**Comment by superdave7380** [comment]
I'm not sure what answer I can give you. After the update, I restarted Sublime as usual. But the Docs options are still greyed out. I don't have any more information than that, sorry.

**Comment by xjsender** [comment]
@superdave7380 , I just update the content in the release 3.3.7, you need to reinstall the 3.3.7 and then you can see how it works.

**Comment by superdave7380** [comment]
That did it. I uninstalled and reinstalled the plugin. All good now. Thanks for your help!
